"use client";
import { useState, useCallback, useEffect } from "react";
const GOLD="#D4A843",BLACK="#0D0D0D",CHARCOAL="#1A1A1A",GREEN="#2ECC71",RED_C="#E74C3C";

const CARDS=[
  {front:"What is position management?",back:"The process of handling a trade from entry to exit. It's what happens AFTER the perfect setup triggers — and it's where most traders actually win or lose. Four phases: Enter, Average, Scale, Runners. Each phase needs its own decision logic."},
  {front:"Why can't 'set and forget' work for options?",back:"Every day you hold a position, time decays (theta), price moves, and confluences shift. Active management isn't optional — it's the job. Set-and-forget works for index investing, not for leveraged derivatives with expiration dates."},
  {front:"What's a starter position?",back:"The smaller initial size you enter with — gives you exposure without overcommitting. Even clean setups can retrace before heading to target. A starter leaves you capital to improve your cost basis on a pullback."},
  {front:"Why shouldn't you enter full size at the trigger?",back:"Because even the cleanest setup can retrace before going to target. If you entered full size, you have no capital left to take a better entry on the pullback. A starter keeps you nimble and prepared to execute if the trade moves against you temporarily."},
  {front:"What does 'averaging up' mean?",back:"Buying more contracts at a HIGHER premium than your original entry. This increases your cost basis. You're adding because the trade is CONFIRMING — a signal has fired and the thesis is developing in your direction."},
  {front:"What does 'averaging down' mean?",back:"Buying more contracts at a LOWER premium than your original entry. This decreases your cost basis. You're adding because the chart has offered a better entry — NOT because you're hoping price comes back. The chart must give you a signal."},
  {front:"What's the #1 rule for averaging?",back:"Do it with INTENTION based on chart confluences — never based on emotion. 'It went red and I'm in calls so I'll average down' is how accounts blow up. The chart must provide an actionable signal."},
  {front:"What's the if-then cascade?",back:"The logic Adex uses to decide when to average. 'If there's a setup that triggers, then it gets to target. What does that make the next candle look like?' You chain if-then statements up through the timeframes until you reach your higher-TF trigger."},
  {front:"Walk through the if-then cascade for an hourly outside hammer.",back:"IF the hourly triggers 3-2u and gets to target (prior day high), THEN the day becomes a 2u. IF the day triggers 2u, THEN it becomes a daily CCRP. IF the daily CCRP triggers, THEN the thesis unlocks the 2-week 3-1-2u setup. That chain is your justification to add."},
  {front:"What's the difference between Invalidation and Reassessment?",back:"Invalidation = the LOW of your trigger candle (for bullish). A candle CLOSE below this kills the thesis. Exit immediately. Reassessment = the 50% of your trigger candle. Not an auto-exit — a decision point where you re-check confluences and decide whether to hold, trim, or cut."},
  {front:"Why is 50% of the trigger candle the reassessment level?",back:"Because when price trades below 50%, you've structurally lost more than you've gained within that candle's range. The bias is shifting. You're still technically in the trade until the low breaks, but the setup is weakening — which is your signal to re-check everything before things get worse."},
  {front:"You're below the 50% reassessment but above the invalidation low. What now?",back:"Reassessment — it's decision time, not exit time. Check: (1) Are my bull/bear confluences still intact? (2) Has the multi-TF picture shifted? (3) Given the -30% rule, should I hold, cut 50%, or exit? Reassess = think, not panic."},
  {front:"What's 'scaling in'?",back:"Gradually increasing position size as the trade develops. Different from averaging down — scaling in happens on CONFIRMATION (the if-then chain firing), not on drawdown. You add when signals tell you the trade is unfolding, not when premium is cheap."},
  {front:"What's 'scaling out'?",back:"Trimming in tiers to secure profits while leaving runners. Ensures you lock in gains AND keep exposure to the higher-TF target. Scaling out reduces stress because you've 'paid yourself' for the trade — whatever the runner does is bonus."},
  {front:"When should you scale IN (add to position)?",back:"1) A lower-TF signal triggers that reinforces your higher-TF thesis. 2) Price reaches OTE / 50% reassessment and shows a reversal signal (CCRP, hammer). 3) A new higher-TF candle opens with a setup aligned to your thesis."},
  {front:"When should you scale OUT (trim)?",back:"1) Price hits a chart target (first gap fill, first resistance). 2) Position crosses major % milestones (+30%, +50%, +100%). 3) Thesis completes on a smaller TF but higher-TF target is still in play — trim, keep runner."},
  {front:"What does 'working the position' mean?",back:"Actively engaging with the trade through every meaningful candle — averaging up/down, trimming, adding — as long as the thesis hasn't invalidated and you have time in your favor. The market gives you opportunities; you work them."},
  {front:"What are the pre-conditions for working a position?",back:"1) Thesis hasn't invalidated (still above the trigger candle's low for bullish). 2) You have time (contracts expire far enough out that theta isn't eating you alive). 3) Confluences still favor your direction. If any of these break, stop working and apply risk rules."},
  {front:"What was the $CMG thesis setup?",back:"Multi-TF confluence: daily outside 2-day closing at high (3-2u setup), weekly 1-3 closed at high, 2-week 3-1 setup, 3-week potential 3-2u, 4-week potential 2-2 rev, monthly potential CCRP, at BOTTOM of broadening formation. Entered July $55 calls at $1.60 when daily triggered 3-2u."},
  {front:"Why did Adex average down $CMG at $0.98?",back:"Not because it was cheap. Because an hourly outside hammer was closing at its high — the if-then cascade said: IF hourly triggers 3-2u → day triggers 2u → day becomes daily CCRP → unlocks the 2-week thesis. The chart gave a signal, so he added."},
  {front:"Why did Adex average UP after the CCRP confirmed, even though already in profit?",back:"Because the TRUE trigger (the 2-week 3-1-2u feeding into monthly 2-2 rev) hadn't fired yet. Everything up to the CCRP was just runway to the real setup. You can keep building a position up to your primary trigger, not just before the first entry."},
  {front:"$CMG went from -40% to +20% to -30% again (back to reassessment). Did Adex cut?",back:"No. Price was still above 50% of the trigger candle (technically above reassessment). Still more bullish than bearish confluences. Thesis not invalidated. He held without re-averaging this time — and price reversed off 50% back to new highs."},
  {front:"How long did the $CMG trade take from entry to final target?",back:"About 6 weeks — mid-May to late June / early July. During that time it swung from breakeven to -40% to +20% to -30% to +12% to +46% to +150% — all WITHOUT the original thesis invalidating. That's what working a position looks like."},
  {front:"Some members were up 100%+ while Adex was only up 46% on $CMG runners. Why?",back:"They averaged in more aggressively at the OTE reassessment bounce (the second -30% point where price reversed off 50%). Averaging at the reassessment level when the thesis is still valid — and confirmation appears — gives a much better cost basis for the final leg to target."},
  {front:"Can you 'average forever' on a losing position?",back:"No. Averaging requires (1) the thesis hasn't invalidated, (2) the chart is giving you an actionable signal to add, and (3) you have time left on your contracts. If the thesis invalidates (candle close below the low), you stop averaging and exit. Working a position doesn't mean denying reality."},
  {front:"What's the lesson from $CMG for beginners?",back:"If you'd cut at -40%, you missed 150%. If you'd cut at -30% after the bounce, you missed 150%. The ability to 'work a position' through noise when the thesis is intact is what separates scalper mindsets from swing trader mindsets. Process over outcomes."},
  {front:"What's the emotional value of scaling out?",back:"Once you've locked in gains on part of the position, the remaining runner is 'free.' You've already paid yourself. This removes the stress of micromanagement and lets you hold through retracements that would have panicked a full-size position. Freedom = better decisions."},
];

export default function Flashcards(){
  const[deck,setDeck]=useState([...CARDS]);const[idx,setIdx]=useState(0);const[flipped,setFlipped]=useState(false);
  const[known,setKnown]=useState(new Set());const[reviewing,setReviewing]=useState(new Set());const[animDir,setAnimDir]=useState(null);
  const current=deck[idx];const total=deck.length;const progress=((known.size+reviewing.size)/CARDS.length)*100;
  const flip=useCallback(()=>setFlipped(f=>!f),[]);
  const next=useCallback((st)=>{const id=deck[idx].front;if(st==="known"){setKnown(p=>new Set([...p,id]));setReviewing(p=>{const n=new Set(p);n.delete(id);return n;});}else{setReviewing(p=>new Set([...p,id]));setKnown(p=>{const n=new Set(p);n.delete(id);return n;});}setAnimDir(st==="known"?"right":"left");setTimeout(()=>{setFlipped(false);setAnimDir(null);setIdx(i=>(i+1)%total);},250);},[deck,idx,total]);
  const shuffle=useCallback(()=>{setDeck([...CARDS].sort(()=>Math.random()-0.5));setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  const reset=useCallback(()=>{setDeck([...CARDS]);setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  useEffect(()=>{const h=(e)=>{if(e.code==="Space"){e.preventDefault();flip();}if(e.code==="ArrowRight")next("known");if(e.code==="ArrowLeft")next("review");};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h);},[flip,next]);
  return(
    <div style={{minHeight:"100vh",background:`linear-gradient(135deg,${BLACK} 0%,#1a1510 100%)`,fontFamily:"'Segoe UI',system-ui,sans-serif",padding:"20px",boxSizing:"border-box"}}>
      <div style={{textAlign:"center",marginBottom:20}}><div style={{color:GOLD,fontSize:11,letterSpacing:3,fontWeight:700,marginBottom:4}}>ADEXTRADES UNIVERSITY</div><div style={{color:"#fff",fontSize:22,fontWeight:700}}>Lesson #15 Flashcards</div><div style={{color:"#888",fontSize:13,marginTop:2}}>Position Management</div></div>
      <div style={{maxWidth:500,margin:"0 auto 16px",display:"flex",gap:12,alignItems:"center"}}><div style={{flex:1,height:6,background:"#2a2a2a",borderRadius:3,overflow:"hidden"}}><div style={{height:"100%",width:`${progress}%`,background:`linear-gradient(90deg,${GOLD},#e8c85a)`,borderRadius:3,transition:"width 0.4s"}}/></div><div style={{color:"#888",fontSize:12,whiteSpace:"nowrap"}}>{known.size+reviewing.size}/{CARDS.length}</div></div>
      <div style={{maxWidth:500,margin:"0 auto 20px",display:"flex",justifyContent:"center",gap:20}}>{[{c:GREEN,l:"Mastered",v:known.size},{c:RED_C,l:"Review",v:reviewing.size},{c:"#555",l:"Unseen",v:CARDS.length-known.size-reviewing.size}].map(({c,l,v})=>(<div key={l} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:8,height:8,borderRadius:"50%",background:c}}/><span style={{color:"#aaa",fontSize:12}}>{l}: {v}</span></div>))}</div>
      <div style={{maxWidth:500,margin:"0 auto",perspective:1000}}>
        <div onClick={flip} style={{cursor:"pointer",position:"relative",height:320,transformStyle:"preserve-3d",transition:animDir?"transform 0.25s, opacity 0.25s":"transform 0.5s",transform:`${flipped?"rotateY(180deg)":"rotateY(0)"} ${animDir==="right"?"translateX(60px)":animDir==="left"?"translateX(-60px)":""}`,opacity:animDir?0.3:1}}>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",background:`linear-gradient(145deg,${CHARCOAL},#222)`,border:`2px solid ${GOLD}40`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"30px 28px",boxSizing:"border-box"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:16,opacity:0.7}}>QUESTION</div><div style={{color:"#fff",fontSize:17,textAlign:"center",lineHeight:1.5,fontWeight:500}}>{current.front}</div><div style={{color:"#666",fontSize:11,marginTop:"auto",paddingTop:12}}>Tap to flip</div></div>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",transform:"rotateY(180deg)",background:`linear-gradient(145deg,#1a1508,#1e1a10)`,border:`2px solid ${GOLD}`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"22px 26px",boxSizing:"border-box",overflow:"auto"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:10}}>ANSWER</div><div style={{color:"#e8e0d0",fontSize:13,textAlign:"center",lineHeight:1.6}}>{current.back}</div></div>
        </div>
      </div>
      <div style={{textAlign:"center",color:"#666",fontSize:12,margin:"12px 0"}}>Card {idx+1} of {total}</div>
      <div style={{maxWidth:500,margin:"0 auto",display:"flex",gap:12,justifyContent:"center"}}>{[{label:"← Review Again",color:RED_C,action:"review"},{label:"Got It →",color:GREEN,action:"known"}].map(({label,color,action})=>(<button key={action} onClick={()=>next(action)} style={{flex:1,padding:"14px 0",background:"transparent",border:`2px solid ${color}`,color,borderRadius:10,fontSize:14,fontWeight:700,cursor:"pointer",transition:"all 0.2s"}} onMouseEnter={e=>e.target.style.background=color+"20"} onMouseLeave={e=>e.target.style.background="transparent"}>{label}</button>))}</div>
      <div style={{maxWidth:500,margin:"16px auto 0",display:"flex",gap:10,justifyContent:"center"}}><button onClick={shuffle} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>🔀 Shuffle</button><button onClick={reset} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>↺ Reset</button></div>
      <div style={{textAlign:"center",color:"#444",fontSize:11,marginTop:16}}>Space = flip · ← = review · → = got it</div>
    </div>);
}
