"use client";
import { useState, useCallback, useEffect } from "react";
const GOLD="#D4A843",BLACK="#0D0D0D",CHARCOAL="#1A1A1A",GREEN="#2ECC71",RED_C="#E74C3C";

const CARDS=[
  {front:"What is an option?",back:"A contract that gives you the buyer the RIGHT (but not the obligation) to buy or sell a stock at a certain price on or before a specific date. In plain terms: a bet that a stock will be at a specific price by a certain date."},
  {front:"How many shares does 1 options contract represent?",back:"100 shares. Always. This never changes. When you see a premium listed as '$2.50,' that's PER SHARE — multiply by 100 to get the total cost of the contract ($250)."},
  {front:"You see a premium of $2.44. What's the total cost of 1 contract?",back:"$244. Premium × 100 shares = total contract cost. $2.44 × 100 = $244. Always multiply by 100 to get the real cost before entering a trade."},
  {front:"What's a long call?",back:"A bullish bet. It gives you the right to BUY 100 shares at the strike price. You profit when the stock goes UP. Max loss = premium paid. Max profit = unlimited (stock can keep going up)."},
  {front:"What's a long put?",back:"A bearish bet. It gives you the right to SELL 100 shares at the strike price. You profit when the stock goes DOWN. Max loss = premium paid. Max profit = large but capped (stock can only go to $0)."},
  {front:"Calls = long the stock. Puts = ?",back:"Puts = shorting the stock. Buying puts is functionally similar to short-selling — you profit when price drops. But with puts, your max loss is capped at the premium paid (unlike short-selling, which has unlimited downside)."},
  {front:"What are the three reasons to trade options instead of stocks?",back:"1) Less capital — control 100 shares for a fraction of the price. 2) Higher leveraged returns — a 5% stock move can mean 25–100%+ on the contract. 3) Insurance / hedging — buy puts to protect long stock positions against crashes."},
  {front:"Stocks vs options: expiration?",back:"Stocks have NO expiration — you can hold forever (unless the company goes to $0 or bankrupt). Options ALWAYS have an expiration date — the contract can expire worthless if your bet doesn't pay off."},
  {front:"What does BTO mean?",back:"Buy To Open. You're opening a new long position by buying a contract. This is what you'll do most often when trading long calls and long puts."},
  {front:"What does STC mean?",back:"Sell To Close. You're closing an existing long position by selling your contract. Together with BTO, these are the two terms you'll use 95% of the time."},
  {front:"What's the difference between bid and ask?",back:"Bid = price a BUYER is willing to pay for the contract (what you sell into). Ask = price a SELLER wants to receive (what you buy at). You want the spread between them to be SMALL (liquid contract)."},
  {front:"What's the 'spread' in an options chain?",back:"The difference between bid and ask. Bid $2.35, ask $2.44 = spread of $0.09 ($9 per contract). Small spreads = liquid, tradeable. Large spreads = illiquid, avoid — you'll lose money to the spread alone."},
  {front:"What's Adex's fill rule?",back:"BUY at the ASK for instant fills, SELL at the BID for instant exits. When your thesis triggers, pay the ask to get in immediately. When price hits your target, sell at the bid to get out fast. Speed matters more than saving a few cents."},
  {front:"Why is spread size critical?",back:"Because you buy at the ask and sell at the bid. A $0.09 spread means you're down $9 per contract the moment you enter. On wide-spread contracts, price can move in your favor and you STILL exit at a loss because you bought high and had to sell low."},
  {front:"What's the strike price?",back:"The price at which the option can be exercised — the price you agreed to buy (calls) or sell (puts) 100 shares at. If a stock is at $245 and you own a $240 call, your strike is $240."},
  {front:"What's the break-even price?",back:"The price the stock must surpass for you to avoid a loss on the contract at expiration. Always HIGHER than the strike for calls (you also need to cover the premium paid). Example: $235 call with $2.44 premium → break-even = $237.44."},
  {front:"What's intrinsic value?",back:"The in-the-money portion of a contract. For calls: Stock price − Strike price (if positive). For puts: Strike price − Stock price (if positive). If negative, intrinsic = $0 and the contract is worthless at expiration."},
  {front:"Stock at $245. You own a $240 call expiring today. What's the intrinsic value?",back:"$5 per share, or $500 total per contract. Intrinsic = Stock − Strike = $245 − $240 = $5. Multiply by 100 shares = $500. At expiration, that's exactly what the contract is worth."},
  {front:"Stock at $245. You own a $250 call expiring today. What's it worth?",back:"$0. Worthless. You don't exercise the right to buy at $250 when you can just buy at the market price of $245. The call is out-of-the-money and expires worthless. You lose the premium you paid."},
  {front:"What's extrinsic value?",back:"The time value component of a premium — the portion added because the contract hasn't expired yet. Time = possibility. Anything can happen before expiration (earnings, news), so the market prices that uncertainty into the premium. Extrinsic decays to $0 as expiration approaches (theta)."},
  {front:"Premium = Intrinsic + ___?",back:"Extrinsic (time value). Every options premium is the sum of these two components. An option expiring TODAY has only intrinsic value (or zero if OTM). An option with 2 weeks left has intrinsic + extrinsic. The extra premium is what you pay for the time."},
  {front:"Do you have to hold an option until expiration?",back:"No. You can sell (close) any time before or on the expiration date. You could buy at 9:30 AM and sell at 9:32 AM if you wanted. Most active traders never hold to expiration."},
  {front:"Do you need to own the underlying stock to trade options on it?",back:"No. You can trade options on ANY ticker without owning any shares. Costco at $1,000 but you don't own any? No problem — you can still buy Costco calls or puts if the setup looks good."},
  {front:"What's the maximum you can lose on a long call or long put?",back:"The premium you paid. Nothing more. No margin required. If you paid $244 for one contract and the setup fails, your max loss is $244. You can't lose more than you put in on long options positions."},
];

export default function Flashcards(){
  const[deck,setDeck]=useState([...CARDS]);const[idx,setIdx]=useState(0);const[flipped,setFlipped]=useState(false);
  const[known,setKnown]=useState(new Set());const[reviewing,setReviewing]=useState(new Set());const[animDir,setAnimDir]=useState(null);
  const current=deck[idx];const total=deck.length;const progress=((known.size+reviewing.size)/CARDS.length)*100;
  const flip=useCallback(()=>setFlipped(f=>!f),[]);
  const next=useCallback((st)=>{const id=deck[idx].front;if(st==="known"){setKnown(p=>new Set([...p,id]));setReviewing(p=>{const n=new Set(p);n.delete(id);return n;});setAnimDir("right");setTimeout(()=>{setFlipped(false);setAnimDir(null);setDeck(prev=>{const nd=[...prev];nd.splice(idx,1);return nd.length?nd:prev;});setIdx(i=>i>=deck.length-1?0:i);},250);}else{setReviewing(p=>new Set([...p,id]));setKnown(p=>{const n=new Set(p);n.delete(id);return n;});setAnimDir("left");setTimeout(()=>{setFlipped(false);setAnimDir(null);setDeck(prev=>{const nd=[...prev];const card=nd.splice(idx,1)[0];nd.push(card);return nd;});setIdx(i=>i>=deck.length-1?0:i);},250);}},[deck,idx]);
  const shuffle=useCallback(()=>{setDeck([...CARDS].sort(()=>Math.random()-0.5));setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  const reset=useCallback(()=>{setDeck([...CARDS]);setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  useEffect(()=>{const h=(e)=>{if(e.code==="Space"){e.preventDefault();flip();}if(e.code==="ArrowRight")next("known");if(e.code==="ArrowLeft")next("review");};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h);},[flip,next]);
  return(
    <div style={{minHeight:"100vh",background:`linear-gradient(135deg,${BLACK} 0%,#1a1510 100%)`,fontFamily:"'Segoe UI',system-ui,sans-serif",padding:"20px",boxSizing:"border-box"}}>
      <div style={{textAlign:"center",marginBottom:20}}><div style={{color:GOLD,fontSize:11,letterSpacing:3,fontWeight:700,marginBottom:4}}>ADEXTRADES UNIVERSITY</div><div style={{color:"#fff",fontSize:22,fontWeight:700}}>Lesson #12 Flashcards</div><div style={{color:"#888",fontSize:13,marginTop:2}}>Intro to Options</div></div>
      <div style={{maxWidth:500,margin:"0 auto 16px",display:"flex",gap:12,alignItems:"center"}}><div style={{flex:1,height:6,background:"#2a2a2a",borderRadius:3,overflow:"hidden"}}><div style={{height:"100%",width:`${progress}%`,background:`linear-gradient(90deg,${GOLD},#e8c85a)`,borderRadius:3,transition:"width 0.4s"}}/></div><div style={{color:"#888",fontSize:12,whiteSpace:"nowrap"}}>{known.size+reviewing.size}/{CARDS.length}</div></div>
      <div style={{maxWidth:500,margin:"0 auto 20px",display:"flex",justifyContent:"center",gap:20}}>{[{c:GREEN,l:"Mastered",v:known.size},{c:RED_C,l:"Review",v:reviewing.size},{c:"#555",l:"Unseen",v:CARDS.length-known.size-reviewing.size}].map(({c,l,v})=>(<div key={l} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:8,height:8,borderRadius:"50%",background:c}}/><span style={{color:"#aaa",fontSize:12}}>{l}: {v}</span></div>))}</div>
      <div style={{maxWidth:500,margin:"0 auto",perspective:1000}}>
        <div onClick={flip} style={{cursor:"pointer",position:"relative",height:320,transformStyle:"preserve-3d",transition:animDir?"transform 0.25s, opacity 0.25s":"transform 0.5s",transform:`${flipped?"rotateY(180deg)":"rotateY(0)"} ${animDir==="right"?"translateX(60px)":animDir==="left"?"translateX(-60px)":""}`,opacity:animDir?0.3:1}}>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",background:`linear-gradient(145deg,${CHARCOAL},#222)`,border:`2px solid ${GOLD}40`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"30px 28px",boxSizing:"border-box"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:16,opacity:0.7}}>QUESTION</div><div style={{color:"#fff",fontSize:17,textAlign:"center",lineHeight:1.5,fontWeight:500}}>{current.front}</div><div style={{color:"#666",fontSize:11,marginTop:"auto",paddingTop:12}}>Tap to flip</div></div>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",transform:"rotateY(180deg)",background:`linear-gradient(145deg,#1a1508,#1e1a10)`,border:`2px solid ${GOLD}`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"22px 26px",boxSizing:"border-box",overflow:"auto"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:10}}>ANSWER</div><div style={{color:"#e8e0d0",fontSize:13,textAlign:"center",lineHeight:1.6}}>{current.back}</div></div>
        </div>
      </div>
      <div style={{textAlign:"center",color:"#666",fontSize:12,margin:"12px 0"}}>Card {idx+1} of {total}</div>
      <div style={{maxWidth:500,margin:"0 auto",display:"flex",gap:12,justifyContent:"center"}}>{[{label:"← Review Again",color:RED_C,action:"review"},{label:"Got It →",color:GREEN,action:"known"}].map(({label,color,action})=>(<button key={action} onClick={()=>next(action)} style={{flex:1,padding:"14px 0",background:"transparent",border:`2px solid ${color}`,color,borderRadius:10,fontSize:14,fontWeight:700,cursor:"pointer",transition:"all 0.2s"}} onMouseEnter={e=>e.target.style.background=color+"20"} onMouseLeave={e=>e.target.style.background="transparent"}>{label}</button>))}</div>
      <div style={{maxWidth:500,margin:"16px auto 0",display:"flex",gap:10,justifyContent:"center"}}><button onClick={shuffle} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>🔀 Shuffle</button><button onClick={reset} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>↺ Reset</button></div>
      <div style={{textAlign:"center",color:"#444",fontSize:11,marginTop:16}}>Space = flip · ← = review · → = got it</div>
    </div>);
}
