"use client";
import { useState, useCallback, useEffect } from "react";
const GOLD="#D4A843",BLACK="#0D0D0D",CHARCOAL="#1A1A1A",GREEN="#2ECC71",RED_C="#E74C3C";

const CARDS=[
  {front:"What is sector rotation?",back:"The movement of invested money from stocks in one sector to another. The economy moves in cycles, and certain companies benefit depending on where we are in that cycle. Institutions rotate capital to maximize returns — your job is to trade alongside them."},
  {front:"How many sectors are in the S&P 500? How many industries?",back:"11 sectors and 69 industries. Sectors are broad categories (Technology, Healthcare, Financials). Industries are specific divisions within a sector (Technology → Semiconductors, Software, Cybersecurity)."},
  {front:"Name the 11 S&P 500 sectors and their SPDR ETF tickers.",back:"Technology (XLK), Healthcare (XLV), Financials (XLF), Consumer Discretionary (XLY), Consumer Staples (XLP), Energy (XLE), Industrials (XLI), Materials (XLB), Utilities (XLU), Real Estate (XLRE), Communications (XLC)."},
  {front:"What's the difference between a sector and an industry?",back:"A sector is a broad category (e.g., Technology). An industry is a specific division within a sector (e.g., Semiconductors, Software, Cybersecurity are all industries within Technology). Think of industries as subsectors."},
  {front:"What are the four tiers of the top-down approach?",back:"1) Futures (ES, NQ, YM, RTY) — overall market sentiment. 2) Index ETFs (SPY, QQQ, DIA, IWM) — broad market strength. 3) Sectors (SPDR, iShares, VanEck ETFs) — where money is flowing. 4) Stocks — within the strongest/weakest sectors."},
  {front:"What are the four futures markets you should chart?",back:"ES (E-mini S&P 500 — broad market), NQ (E-mini Nasdaq 100 — tech-heavy), YM (Dow Jones Futures — 30 blue chips), RTY (Russell 2000 Futures — small caps)."},
  {front:"Why does the futures market matter for stock traders?",back:"Futures trade 23 hours a day, 6 days a week. They give insight into market sentiment and potential opening prices. If ES is up overnight, SPY has a high probability of gapping up. If NQ is up, QQQ/tech stocks gap up. Futures predict the next-session open."},
  {front:"What does it mean if $NQ is trading higher overnight?",back:"There's a high probability that $QQQ (and technology stocks broadly) will gap up when the market opens. $NQ tracks the Nasdaq 100, which is heavily weighted toward tech. Overnight futures strength typically carries into the next session's open."},
  {front:"What's the difference between an index and an index ETF?",back:"An index (like the S&P 500) is a benchmark — you can't directly trade it. An index ETF (like $SPY) tracks that benchmark 1:1 and IS directly tradable via shares and options. $SPY tracks S&P 500, $QQQ tracks Nasdaq 100, $DIA tracks Dow Jones, $IWM tracks Russell 2000."},
  {front:"Why should you check multiple ETF families (SPDR, iShares, VanEck)?",back:"Different families hold different stocks. $XLY (SPDR) might include $LOW while $IYK (iShares Consumer Discretionary) doesn't. Charting both catches discrepancies and builds confluence. If $XLF and $IYF both show bullish setups, that's stronger conviction than either alone."},
  {front:"What's the SPDR family of sector ETFs?",back:"The SPDR Select Sector ETFs. There are 11 of them (one per S&P 500 sector): XLK, XLV, XLF, XLY, XLP, XLE, XLI, XLB, XLU, XLRE, XLC. Each mirrors its respective sector of the S&P 500."},
  {front:"What's $SMH and why is it useful?",back:"$SMH is the VanEck Semiconductor ETF. It holds $NVDA, $AMD, $TSM, $INTC, $MU, $AVGO, $ASML, $SMCI, etc. If $SMH triggers a Strat combo (e.g., 2-1-2d), the semiconductor stocks inside typically follow. It's a single-chart way to track the entire industry."},
  {front:"What is a sympathy relationship?",back:"When the price movement of one asset influences another because they're related. Three types: 1) Marketwide (SPY ↔ QQQ share top holdings). 2) Competitor ($V ↔ $MA). 3) Sector/Industry (Nvidia earnings affect $AMD, $TSM, $MU, $AVGO)."},
  {front:"If $NVDA has great earnings and gaps up, what happens to $AMD, $TSM, $MU?",back:"They typically gap up too — a sector/industry sympathy relationship. Strong Nvidia earnings signal strong demand for semiconductors broadly, so competitors and suppliers benefit. $SMH also gaps up, dragging all semi names with it."},
  {front:"Can sympathy relationships be NEGATIVE?",back:"Yes. When Trump cut the EV tax credit, $F and $GM (gas-focused) benefited, but $TSLA (which relied on the credit) went DOWN. Sympathy isn't always same-direction — it depends on WHY the stocks are related. Understand the relationship before assuming they'll move together."},
  {front:"If Microsoft and Apple both report bad earnings, which indices suffer?",back:"All three major indices: $SPY, $QQQ, and $DIA. Apple and Microsoft are heavily weighted in all three (different weightings, but significant in each). $ES, $NQ, and $YM futures would drop overnight, and all three ETFs would gap down."},
  {front:"What's the 'market fell today' joke in the AdexTrades community?",back:"When retail says 'the market fell today,' they mean SPY/QQQ. But real estate (or whatever sector was green) doesn't know what they're talking about. Money always flows SOMEWHERE. That's the whole point of sector rotation — even in 'down' days, something is up."},
  {front:"What's Adex's first confluence when analyzing a chart?",back:"Sector strength. The sector has to align before anything else matters. His last confluence (the icing on the cake) is Full Timeframe Continuity (FTFC). Everything in between — Strat combos, OTE, gap fills, CCRP — happens between those two bookends."},
  {front:"Why does Adex call out sectors before tickers in live sessions?",back:"Because the sector determines the watchlist. If it's an 'XLRE day,' focus on real estate names ($PLLD, $FRT, $KIM). If it's an 'XLE day,' focus on energy. You don't chase $TSLA or $NVDA unless their sector is the one showing strength."},
  {front:"A sector triggers a 2-1-2d on the daily. You see a semi stock has a 1-3-2 rev strat setting up. Is that a good sympathy trade?",back:"Potentially yes — both point to downside. When both the sector ETF and the individual stock have Strat setups pointing the same direction, that's additional confluence. Even if the exact combo differs (2-1-2d vs. 1-3-2), the directional alignment is what matters."},
];

export default function Flashcards(){
  const[deck,setDeck]=useState([...CARDS]);const[idx,setIdx]=useState(0);const[flipped,setFlipped]=useState(false);
  const[known,setKnown]=useState(new Set());const[reviewing,setReviewing]=useState(new Set());const[animDir,setAnimDir]=useState(null);
  const current=deck[idx];const total=deck.length;const progress=((known.size+reviewing.size)/CARDS.length)*100;
  const flip=useCallback(()=>setFlipped(f=>!f),[]);
  const next=useCallback((st)=>{const id=deck[idx].front;if(st==="known"){setKnown(p=>new Set([...p,id]));setReviewing(p=>{const n=new Set(p);n.delete(id);return n;});}else{setReviewing(p=>new Set([...p,id]));setKnown(p=>{const n=new Set(p);n.delete(id);return n;});}setAnimDir(st==="known"?"right":"left");setTimeout(()=>{setFlipped(false);setAnimDir(null);setIdx(i=>(i+1)%total);},250);},[deck,idx,total]);
  const shuffle=useCallback(()=>{setDeck([...CARDS].sort(()=>Math.random()-0.5));setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  const reset=useCallback(()=>{setDeck([...CARDS]);setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  useEffect(()=>{const h=(e)=>{if(e.code==="Space"){e.preventDefault();flip();}if(e.code==="ArrowRight")next("known");if(e.code==="ArrowLeft")next("review");};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h);},[flip,next]);
  return(
    <div style={{minHeight:"100vh",background:`linear-gradient(135deg,${BLACK} 0%,#1a1510 100%)`,fontFamily:"'Segoe UI',system-ui,sans-serif",padding:"20px",boxSizing:"border-box"}}>
      <div style={{textAlign:"center",marginBottom:20}}><div style={{color:GOLD,fontSize:11,letterSpacing:3,fontWeight:700,marginBottom:4}}>ADEXTRADES UNIVERSITY</div><div style={{color:"#fff",fontSize:22,fontWeight:700}}>Lesson #9 Flashcards</div><div style={{color:"#888",fontSize:13,marginTop:2}}>Sector Rotation</div></div>
      <div style={{maxWidth:500,margin:"0 auto 16px",display:"flex",gap:12,alignItems:"center"}}><div style={{flex:1,height:6,background:"#2a2a2a",borderRadius:3,overflow:"hidden"}}><div style={{height:"100%",width:`${progress}%`,background:`linear-gradient(90deg,${GOLD},#e8c85a)`,borderRadius:3,transition:"width 0.4s"}}/></div><div style={{color:"#888",fontSize:12,whiteSpace:"nowrap"}}>{known.size+reviewing.size}/{CARDS.length}</div></div>
      <div style={{maxWidth:500,margin:"0 auto 20px",display:"flex",justifyContent:"center",gap:20}}>{[{c:GREEN,l:"Mastered",v:known.size},{c:RED_C,l:"Review",v:reviewing.size},{c:"#555",l:"Unseen",v:CARDS.length-known.size-reviewing.size}].map(({c,l,v})=>(<div key={l} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:8,height:8,borderRadius:"50%",background:c}}/><span style={{color:"#aaa",fontSize:12}}>{l}: {v}</span></div>))}</div>
      <div style={{maxWidth:500,margin:"0 auto",perspective:1000}}>
        <div onClick={flip} style={{cursor:"pointer",position:"relative",height:320,transformStyle:"preserve-3d",transition:animDir?"transform 0.25s, opacity 0.25s":"transform 0.5s",transform:`${flipped?"rotateY(180deg)":"rotateY(0)"} ${animDir==="right"?"translateX(60px)":animDir==="left"?"translateX(-60px)":""}`,opacity:animDir?0.3:1}}>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",background:`linear-gradient(145deg,${CHARCOAL},#222)`,border:`2px solid ${GOLD}40`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"30px 28px",boxSizing:"border-box"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:16,opacity:0.7}}>QUESTION</div><div style={{color:"#fff",fontSize:17,textAlign:"center",lineHeight:1.5,fontWeight:500}}>{current.front}</div><div style={{color:"#666",fontSize:11,marginTop:"auto",paddingTop:12}}>Tap to flip</div></div>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",transform:"rotateY(180deg)",background:`linear-gradient(145deg,#1a1508,#1e1a10)`,border:`2px solid ${GOLD}`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"22px 26px",boxSizing:"border-box",overflow:"auto"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:10}}>ANSWER</div><div style={{color:"#e8e0d0",fontSize:13,textAlign:"center",lineHeight:1.6}}>{current.back}</div></div>
        </div>
      </div>
      <div style={{textAlign:"center",color:"#666",fontSize:12,margin:"12px 0"}}>Card {idx+1} of {total}</div>
      <div style={{maxWidth:500,margin:"0 auto",display:"flex",gap:12,justifyContent:"center"}}>{[{label:"← Review Again",color:RED_C,action:"review"},{label:"Got It →",color:GREEN,action:"known"}].map(({label,color,action})=>(<button key={action} onClick={()=>next(action)} style={{flex:1,padding:"14px 0",background:"transparent",border:`2px solid ${color}`,color,borderRadius:10,fontSize:14,fontWeight:700,cursor:"pointer",transition:"all 0.2s"}} onMouseEnter={e=>e.target.style.background=color+"20"} onMouseLeave={e=>e.target.style.background="transparent"}>{label}</button>))}</div>
      <div style={{maxWidth:500,margin:"16px auto 0",display:"flex",gap:10,justifyContent:"center"}}><button onClick={shuffle} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>🔀 Shuffle</button><button onClick={reset} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>↺ Reset</button></div>
      <div style={{textAlign:"center",color:"#444",fontSize:11,marginTop:16}}>Space = flip · ← = review · → = got it</div>
    </div>);
}
