"use client";
import { useState, useCallback, useEffect } from "react";
const GOLD="#D4A843",BLACK="#0D0D0D",CHARCOAL="#1A1A1A",GREEN="#2ECC71",RED_C="#E74C3C";

const CARDS=[
  {front:"What is risk management?",back:"The set of strategies and techniques used to limit potential losses while maximizing potential gains. It's what separates long-term successful traders from gamblers. Smart traders protect capital FIRST and focus on profit potential second."},
  {front:"Why is capital protection more important than profit potential?",back:"If you lose too much too fast, you won't be in the game long enough to capitalize on great opportunities. An account down 50% needs to gain 100% just to get back to breakeven. An account down 80% needs 400%. Preserving capital is mathematically essential for compounding."},
  {front:"What's the allocation range for LOW risk tolerance?",back:"1-2% of your portfolio per trade. Conservative, less risky, reduces exposure to large drawdowns. Ideal for beginners, traders still finding their edge, and those with a long-term investing mindset."},
  {front:"What's the allocation range for MEDIUM risk tolerance?",back:"3-5% of your portfolio per trade. Balances growth with downside risk control. Reserved for traders with consistent, repeatable strategies and proven experience."},
  {front:"What's the allocation range for HIGH risk tolerance?",back:"6%+ of your portfolio per trade. Aggressive — can lead to rapid gains but also big losses. Reserved for highly experienced traders with strong risk controls. Not appropriate for beginners."},
  {front:"What is fixed allocation and why is it useful?",back:"Allocating the same dollar amount to every trade (e.g., $2,000 per position). It removes subjectivity — every position down 50% = $1,000 down, no mental distortion based on position size. Makes it easier to quantify your edge and compare results apples-to-apples."},
  {front:"What is a starter contract?",back:"The initial small position you take before committing more capital. It validates your thesis without full risk exposure. Lets you test the market's reaction and watch the chart before scaling in."},
  {front:"How should you size your starter contract?",back:"It should be the amount you're willing to let go to zero. Not because you're trying to lose it — but because that framing removes emotion. If a starter down 50% makes you anxious, you're overleveraged. Size down until the anxiety disappears."},
  {front:"What does it mean when your starter position makes you anxious?",back:"You're overleveraged. The dollar amount at risk is more than you're actually comfortable with. Reduce position size — take a smaller starter. Anxiety distorts your chart reading and forces bad exits."},
  {front:"What's a 'watchlist position'?",back:"A single contract used essentially as a paid observation post. Real capital, but small enough that emotions don't interfere. You watch the trade play out, and when your thesis confirms, you scale up from there. Popularized on Robinhood but works on any broker."},
  {front:"What is 'averaging up'?",back:"Adding more contracts when the trade is moving in your favor. Locks in leverage on confirmed strength — the thesis is playing out, so you commit more capital to the winning direction."},
  {front:"What is 'averaging down'?",back:"Adding more contracts when the trade moves against you, BUT only when the thesis is still valid (confluences haven't flipped). Just a retracement, not an invalidation. The chart has to tell you to average down — not hope or emotion."},
  {front:"When should you NOT average down?",back:"When your bullish confluences have flipped to bearish (or vice versa). Averaging down into an invalidated thesis isn't 'doubling down' — it's compounding a losing position. Let the chart tell you, not your ego."},
  {front:"What's the single rule for exiting a trade?",back:"The reason you enter is the reason you exit. You exit when the thesis that got you in is no longer valid. Not because you're down a certain percentage. Not because you're bored. Only because the structural reason for the trade has been broken."},
  {front:"What invalidates a 2-1-2u thesis?",back:"A candle CLOSE beyond your invalidation level on your thesis timeframe. Either an outside bar to the downside that closes below the inside bar, OR a 2-2 reversal to the downside. A wick through your level doesn't count — only a full candle close."},
  {front:"What is the -30% rule?",back:"A decision framework used when your trade is down -30% but hasn't technically invalidated yet. Being down 30% on premium usually means your entry wasn't optimal. Before you act, check your bullish and bearish confluences to decide: cut, cut 50%, or average."},
  {front:"Down -30% and confluences have flipped (poor trade). What do you do?",back:"CUT THE TRADE. Don't wait for technical invalidation. Protect capital first. Your objective analysis now shows more signals pointing AGAINST your thesis than for it. Capital protection wins over hope."},
  {front:"Down -30% and confluences are roughly equal (unsure). What do you do?",back:"CUT 50% of your position. Reduce risk while staying in for a possible resolution. Tomorrow the balance might tip further against you — at least you've preserved half your capital for the next setup."},
  {front:"Down -30% and confluences still favor your thesis. What do you do?",back:"AVERAGE UP OR DOWN — but ONLY if you're genuinely comfortable with your strategy. Not because of a rule, because you've seen this play out before. If you're second-guessing, just cut. Experience earns you the right to average down."},
  {front:"What is trimming?",back:"Locking in partial profits at key levels — either chart targets or percentage targets. Reduces risk while keeping exposure to more upside. You can only trim if you have MORE than one contract — otherwise you're just taking profit and closing."},
  {front:"What are the two ways to set trim points?",back:"1) Chart-based (trim at first profit target, close at second profit target). 2) Percentage-based (trim at 20-30%, close at 30%+). Percentage trimming is essential because sometimes you're up 100%+ before hitting your chart target."},
  {front:"What's the beginner trimming framework?",back:"Trim HALF at 20-30% gain, close the rest at 30%+. Not designed to make huge money — designed to build sample size and quantify your edge. 30% wins come faster than 200% wins, so you learn your strategy quicker with more trades."},
  {front:"What's the intermediate trimming framework (10 contracts)?",back:"Trim 5 contracts at 30%. Trim 2-3 more at 40-50%. Close the final 2-3 at 50-100%+. Tiered trimming: take risk off progressively while letting remainders ride higher."},
  {front:"What are 'runners'?",back:"The small portion of a position you leave open after trimming the rest. Once you've locked in gains, the runner is essentially 'free' — you've already booked profit, so anything the runner adds is pure upside. Maximum profit potential, minimum stress."},
  {front:"What does 'let your runners do the heavy lifting' mean?",back:"The biggest wins don't come from hitting first target — they come from runners that ride 200%, 300%, 500%+. But you can only hold a runner comfortably if you've already locked in gains. A stressed runner gets cut early. A 'free' runner can ride through noise."},
  {front:"Why did Adex NOT trim his $UPS trade at +30%?",back:"His final target was $82 with massive multi-timeframe confluence (weekly double-inside, monthly 3-2-2d continuation, 6-week 1-3, etc.). With that many higher-TF signals pointing to $82, he was willing to hold through the retracement. The position went from +30% back to -10% but the thesis hadn't invalidated."},
  {front:"When is it appropriate to watch a +30% trade go back to -10% without cutting?",back:"Only when you have substantial experience AND the multi-timeframe confluence is intact. Beginners should NOT do this — they haven't earned the right to trust higher-TF setups through noise. For beginners, +30% means TRIM. The Adex/Nock approach comes after years of proven process."},
  {front:"What's the difference between money lost and a lesson learned?",back:"Money lost is temporary. A lesson learned compounds. As long as you're following proper risk management, every loss teaches you something about your strategy. A $200 loss that prevents a $2,000 loss later is a win disguised as a loss."},
];

export default function Flashcards(){
  const[deck,setDeck]=useState([...CARDS]);const[idx,setIdx]=useState(0);const[flipped,setFlipped]=useState(false);
  const[known,setKnown]=useState(new Set());const[reviewing,setReviewing]=useState(new Set());const[animDir,setAnimDir]=useState(null);
  const current=deck[idx];const total=deck.length;const progress=((known.size+reviewing.size)/CARDS.length)*100;
  const flip=useCallback(()=>setFlipped(f=>!f),[]);
  const next=useCallback((st)=>{const id=deck[idx].front;if(st==="known"){setKnown(p=>new Set([...p,id]));setReviewing(p=>{const n=new Set(p);n.delete(id);return n;});setAnimDir("right");setTimeout(()=>{setFlipped(false);setAnimDir(null);setDeck(prev=>{const nd=[...prev];nd.splice(idx,1);return nd.length?nd:prev;});setIdx(i=>i>=deck.length-1?0:i);},250);}else{setReviewing(p=>new Set([...p,id]));setKnown(p=>{const n=new Set(p);n.delete(id);return n;});setAnimDir("left");setTimeout(()=>{setFlipped(false);setAnimDir(null);setDeck(prev=>{const nd=[...prev];const card=nd.splice(idx,1)[0];nd.push(card);return nd;});setIdx(i=>i>=deck.length-1?0:i);},250);}},[deck,idx]);
  const shuffle=useCallback(()=>{setDeck([...CARDS].sort(()=>Math.random()-0.5));setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  const reset=useCallback(()=>{setDeck([...CARDS]);setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  useEffect(()=>{const h=(e)=>{if(e.code==="Space"){e.preventDefault();flip();}if(e.code==="ArrowRight")next("known");if(e.code==="ArrowLeft")next("review");};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h);},[flip,next]);
  return(
    <div style={{minHeight:"100vh",background:`linear-gradient(135deg,${BLACK} 0%,#1a1510 100%)`,fontFamily:"'Segoe UI',system-ui,sans-serif",padding:"20px",boxSizing:"border-box"}}>
      <div style={{textAlign:"center",marginBottom:20}}><div style={{color:GOLD,fontSize:11,letterSpacing:3,fontWeight:700,marginBottom:4}}>ADEXTRADES UNIVERSITY</div><div style={{color:"#fff",fontSize:22,fontWeight:700}}>Lesson #14 Flashcards</div><div style={{color:"#888",fontSize:13,marginTop:2}}>Risk Management</div></div>
      <div style={{maxWidth:500,margin:"0 auto 16px",display:"flex",gap:12,alignItems:"center"}}><div style={{flex:1,height:6,background:"#2a2a2a",borderRadius:3,overflow:"hidden"}}><div style={{height:"100%",width:`${progress}%`,background:`linear-gradient(90deg,${GOLD},#e8c85a)`,borderRadius:3,transition:"width 0.4s"}}/></div><div style={{color:"#888",fontSize:12,whiteSpace:"nowrap"}}>{known.size+reviewing.size}/{CARDS.length}</div></div>
      <div style={{maxWidth:500,margin:"0 auto 20px",display:"flex",justifyContent:"center",gap:20}}>{[{c:GREEN,l:"Mastered",v:known.size},{c:RED_C,l:"Review",v:reviewing.size},{c:"#555",l:"Unseen",v:CARDS.length-known.size-reviewing.size}].map(({c,l,v})=>(<div key={l} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:8,height:8,borderRadius:"50%",background:c}}/><span style={{color:"#aaa",fontSize:12}}>{l}: {v}</span></div>))}</div>
      <div style={{maxWidth:500,margin:"0 auto",perspective:1000}}>
        <div onClick={flip} style={{cursor:"pointer",position:"relative",height:320,transformStyle:"preserve-3d",transition:animDir?"transform 0.25s, opacity 0.25s":"transform 0.5s",transform:`${flipped?"rotateY(180deg)":"rotateY(0)"} ${animDir==="right"?"translateX(60px)":animDir==="left"?"translateX(-60px)":""}`,opacity:animDir?0.3:1}}>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",background:`linear-gradient(145deg,${CHARCOAL},#222)`,border:`2px solid ${GOLD}40`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"30px 28px",boxSizing:"border-box"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:16,opacity:0.7}}>QUESTION</div><div style={{color:"#fff",fontSize:17,textAlign:"center",lineHeight:1.5,fontWeight:500}}>{current.front}</div><div style={{color:"#666",fontSize:11,marginTop:"auto",paddingTop:12}}>Tap to flip</div></div>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",transform:"rotateY(180deg)",background:`linear-gradient(145deg,#1a1508,#1e1a10)`,border:`2px solid ${GOLD}`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"22px 26px",boxSizing:"border-box",overflow:"auto"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:10}}>ANSWER</div><div style={{color:"#e8e0d0",fontSize:13,textAlign:"center",lineHeight:1.6}}>{current.back}</div></div>
        </div>
      </div>
      <div style={{textAlign:"center",color:"#666",fontSize:12,margin:"12px 0"}}>Card {idx+1} of {total}</div>
      <div style={{maxWidth:500,margin:"0 auto",display:"flex",gap:12,justifyContent:"center"}}>{[{label:"← Review Again",color:RED_C,action:"review"},{label:"Got It →",color:GREEN,action:"known"}].map(({label,color,action})=>(<button key={action} onClick={()=>next(action)} style={{flex:1,padding:"14px 0",background:"transparent",border:`2px solid ${color}`,color,borderRadius:10,fontSize:14,fontWeight:700,cursor:"pointer",transition:"all 0.2s"}} onMouseEnter={e=>e.target.style.background=color+"20"} onMouseLeave={e=>e.target.style.background="transparent"}>{label}</button>))}</div>
      <div style={{maxWidth:500,margin:"16px auto 0",display:"flex",gap:10,justifyContent:"center"}}><button onClick={shuffle} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>🔀 Shuffle</button><button onClick={reset} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>↺ Reset</button></div>
      <div style={{textAlign:"center",color:"#444",fontSize:11,marginTop:16}}>Space = flip · ← = review · → = got it</div>
    </div>);
}
