"use client";
import { useState, useCallback, useEffect } from "react";
const GOLD="#D4A843",BLACK="#0D0D0D",CHARCOAL="#1A1A1A",GREEN="#2ECC71",RED_C="#E74C3C";

const CARDS=[
  {front:"What does BFIG stand for?",back:"Broadening Formation Inversion Gap. A reversal pattern developed by Abi for catching market turns earlier than a classical market structure shift can confirm them."},
  {front:"What's the main advantage of a BFIG over a classical market structure reversal?",back:"It puts you on BOTH legs of the reversal. Classical MSS waits for lower-high → lower-low → higher-low → higher-high, which means you only catch the last leg. BFIGs let you enter at the inversion point, capturing both the initial counter-move and the trend that follows."},
  {front:"What are the two required conditions for a BFIG?",back:"1) Aggressive displacement into NEW broadening lows (violent break — typically a gap down or full-body bearish candle). 2) IMMEDIATE counter-displacement that OVERLAPS the prior move. Both must be present — one without the other is not a BFIG."},
  {front:"What does 'aggressive displacement into new broadening lows' mean?",back:"A violent break of a relevant prior low — typically with a gap down or full-body bearish candle, not a slow bleed. The market has to actually take out the broadening low with force. A slow grind below doesn't qualify."},
  {front:"What does 'overlap' mean in the BFIG context?",back:"The counter-displacement (Step 2) must cover the same price range as the original displacement (Step 1) — not just bounce, not just wick into it. The upward move must retrace the downward move, flipping the gap from a continuation signal into an inversion signal."},
  {front:"Why is the 'overlap' requirement non-negotiable?",back:"Without overlap, you just have a bounce. The overlap is the signature of institutional order flow reversing direction. It's what converts the broken low from resistance into support and makes it a valid BFIG rather than a failed reversal."},
  {front:"How does a BFIG differ from a BPR or CISD?",back:"BPRs and CISDs are similar concepts but don't require the aggressive break of NEW broadening lows. A BFIG specifically requires that violent break-and-immediate-reclaim sequence. The broadening-low break is what creates the institutional trap that defines the pattern."},
  {front:"What is the AMD cycle?",back:"Accumulation → Manipulation → Distribution. Also called the Power of Three. Accumulation = sideways consolidation where a position is built. Manipulation = sweep of liquidity against the eventual direction (fakeout). Distribution = the real move in the true direction."},
  {front:"Where in the AMD cycle do BFIGs typically fire?",back:"At the end of the MANIPULATION phase — the transition into distribution. The manipulation leg takes out the broadening lows (Step 1), and the distribution leg reverses with aggression (Step 2). You're entering right as the real move begins."},
  {front:"What's the equilibrium of a range?",back:"The 50% midpoint of a range (split high-to-low). Everything ABOVE equilibrium is premium; everything BELOW is discount. In an uptrend, you want to buy in DISCOUNT. In a downtrend, you want to short in PREMIUM."},
  {front:"What's premium vs discount?",back:"Premium = upper half of a range (above 50%). Discount = lower half (below 50%). In an uptrend, buying in discount gives better risk-to-reward because you're entering at favorable price within the range."},
  {front:"Why are BFIGs that fire in DISCOUNT considered A+ setups?",back:"Because you have multiple confluence layers stacked: institutional displacement (the BFIG signal itself), higher-TF context (discounted price in an uptrend), liquidity sweep (external low taken out), and often order block or fair value gap overlap. Multiple reasons to be long, all at once."},
  {front:"What's 'turtle soup'?",back:"When price pokes below a relevant prior low just far enough to trigger stops, then immediately reverses back into range. Named because the turtle sticks its head out, gets snapped at, and retreats. BFIGs often form at turtle-soup locations because that's where institutional liquidity is harvested."},
  {front:"Why is Friday's $DG candle significant?",back:"It redelivered into the gap AND refined the inefficiency — meaning price came back through to fill unfilled orders on its way up. That gives institutional participants a clean entry zone that retail often misses, and the refinement adds confluence to the BFIG."},
  {front:"What was the full $DG confluence stack?",back:"Structural consolidation broken down → Sept 15 external low taken with displacement → New 52-week lows (BFIG Step 1) → Counter-displacement reclaim (BFIG Step 2) → End of manipulation phase → Weekly discount zone → Breaker block + fair value gap → 4-hour flipped supply now acting as demand."},
  {front:"How was $DLTR similar to $DG?",back:"Essentially a carbon copy. Same sector (discount retail). Higher-TF uptrend with redelivery into weekly discount. Took out the April 2025 low at $43.595 — classic turtle soup sweep. Gap down into broadening lows followed by aggressive reclaim = textbook BFIG."},
  {front:"What was the $DE BFIG variant?",back:"Fail-Fill-Flip. Price pushed up to $467-$482, failed to break a lower-TF resistance, broke down to fill the gap at $475, then gapped UP the next day holding near full-body and closed back above the zone that previously rejected it. That reclaim with displacement = BFIG at the local swing level."},
  {front:"What was the invalidation for the $DE BFIG thesis?",back:"Daily close back under $445. As long as price holds that level, the thesis targets the $467-$482 range expansion (potentially higher). If price closes below $445 on a daily basis, the BFIG setup is invalidated."},
  {front:"How is a BFIG a 'trap'?",back:"The aggressive break of broadening lows suggests breakdown to retail eyes. Stops get run below that low. But institutions needed that liquidity to build their real position, and the violent reclaim is them taking the other side — turning the 'breakdown' into the fuel for the real move up."},
  {front:"What lower-timeframe confluence did $DG show?",back:"4-hour chart: price flipped a previous supply area (resistance) into demand (support). What was previously rejecting is now supportive — the inversion of the level's role confirmed the BFIG reading on the higher timeframe."},
  {front:"Why should BFIGs be paired with #TheStrat?",back:"BFIGs tell you WHEN and WHERE institutional order flow is reversing. #TheStrat gives you actionable trigger signals (hammers, CCRPs, 1-3s) that convert that context into a specific entry. Combined, they give you a high-probability directional bias with a clean trigger mechanism."},
  {front:"Can a BFIG fire in premium?",back:"Yes, but it's lower-probability. A BFIG in the discount zone has much better R/R because you're already buying at favorable price. BFIGs in premium tend to have less room to run and a higher invalidation risk. Prioritize BFIGs in discount for the best setups."},
  {front:"What's the final takeaway on BFIGs?",back:"BFIGs catch reversals BEFORE classical market structure shift confirms. They require aggressive violation of new broadening lows followed by immediate countered displacement that OVERLAPS the original move. When paired with premium/discount context, liquidity sweeps, and order block confluence, they're among the highest-probability reversal setups you can find."},
];

export default function Flashcards(){
  const[deck,setDeck]=useState([...CARDS]);const[idx,setIdx]=useState(0);const[flipped,setFlipped]=useState(false);
  const[known,setKnown]=useState(new Set());const[reviewing,setReviewing]=useState(new Set());const[animDir,setAnimDir]=useState(null);
  const current=deck[idx];const total=deck.length;const progress=((known.size+reviewing.size)/CARDS.length)*100;
  const flip=useCallback(()=>setFlipped(f=>!f),[]);
  const next=useCallback((st)=>{const id=deck[idx].front;if(st==="known"){setKnown(p=>new Set([...p,id]));setReviewing(p=>{const n=new Set(p);n.delete(id);return n;});setAnimDir("right");setTimeout(()=>{setFlipped(false);setAnimDir(null);setDeck(prev=>{const nd=[...prev];nd.splice(idx,1);return nd.length?nd:prev;});setIdx(i=>i>=deck.length-1?0:i);},250);}else{setReviewing(p=>new Set([...p,id]));setKnown(p=>{const n=new Set(p);n.delete(id);return n;});setAnimDir("left");setTimeout(()=>{setFlipped(false);setAnimDir(null);setDeck(prev=>{const nd=[...prev];const card=nd.splice(idx,1)[0];nd.push(card);return nd;});setIdx(i=>i>=deck.length-1?0:i);},250);}},[deck,idx]);
  const shuffle=useCallback(()=>{setDeck([...CARDS].sort(()=>Math.random()-0.5));setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  const reset=useCallback(()=>{setDeck([...CARDS]);setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  useEffect(()=>{const h=(e)=>{if(e.code==="Space"){e.preventDefault();flip();}if(e.code==="ArrowRight")next("known");if(e.code==="ArrowLeft")next("review");};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h);},[flip,next]);
  return(
    <div style={{minHeight:"100vh",background:`linear-gradient(135deg,${BLACK} 0%,#1a1510 100%)`,fontFamily:"'Segoe UI',system-ui,sans-serif",padding:"20px",boxSizing:"border-box"}}>
      <div style={{textAlign:"center",marginBottom:20}}><div style={{color:GOLD,fontSize:11,letterSpacing:3,fontWeight:700,marginBottom:4}}>ADEXTRADES UNIVERSITY</div><div style={{color:"#fff",fontSize:22,fontWeight:700}}>Bonus Lesson Flashcards</div><div style={{color:"#888",fontSize:13,marginTop:2}}>Broadening Formation Inversion Gaps (by Abi)</div></div>
      <div style={{maxWidth:500,margin:"0 auto 16px",display:"flex",gap:12,alignItems:"center"}}><div style={{flex:1,height:6,background:"#2a2a2a",borderRadius:3,overflow:"hidden"}}><div style={{height:"100%",width:`${progress}%`,background:`linear-gradient(90deg,${GOLD},#e8c85a)`,borderRadius:3,transition:"width 0.4s"}}/></div><div style={{color:"#888",fontSize:12,whiteSpace:"nowrap"}}>{known.size+reviewing.size}/{CARDS.length}</div></div>
      <div style={{maxWidth:500,margin:"0 auto 20px",display:"flex",justifyContent:"center",gap:20}}>{[{c:GREEN,l:"Mastered",v:known.size},{c:RED_C,l:"Review",v:reviewing.size},{c:"#555",l:"Unseen",v:CARDS.length-known.size-reviewing.size}].map(({c,l,v})=>(<div key={l} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:8,height:8,borderRadius:"50%",background:c}}/><span style={{color:"#aaa",fontSize:12}}>{l}: {v}</span></div>))}</div>
      <div style={{maxWidth:500,margin:"0 auto",perspective:1000}}>
        <div onClick={flip} style={{cursor:"pointer",position:"relative",height:320,transformStyle:"preserve-3d",transition:animDir?"transform 0.25s, opacity 0.25s":"transform 0.5s",transform:`${flipped?"rotateY(180deg)":"rotateY(0)"} ${animDir==="right"?"translateX(60px)":animDir==="left"?"translateX(-60px)":""}`,opacity:animDir?0.3:1}}>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",background:`linear-gradient(145deg,${CHARCOAL},#222)`,border:`2px solid ${GOLD}40`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"30px 28px",boxSizing:"border-box"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:16,opacity:0.7}}>QUESTION</div><div style={{color:"#fff",fontSize:17,textAlign:"center",lineHeight:1.5,fontWeight:500}}>{current.front}</div><div style={{color:"#666",fontSize:11,marginTop:"auto",paddingTop:12}}>Tap to flip</div></div>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",transform:"rotateY(180deg)",background:`linear-gradient(145deg,#1a1508,#1e1a10)`,border:`2px solid ${GOLD}`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"22px 26px",boxSizing:"border-box",overflow:"auto"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:10}}>ANSWER</div><div style={{color:"#e8e0d0",fontSize:13,textAlign:"center",lineHeight:1.6}}>{current.back}</div></div>
        </div>
      </div>
      <div style={{textAlign:"center",color:"#666",fontSize:12,margin:"12px 0"}}>Card {idx+1} of {total}</div>
      <div style={{maxWidth:500,margin:"0 auto",display:"flex",gap:12,justifyContent:"center"}}>{[{label:"← Review Again",color:RED_C,action:"review"},{label:"Got It →",color:GREEN,action:"known"}].map(({label,color,action})=>(<button key={action} onClick={()=>next(action)} style={{flex:1,padding:"14px 0",background:"transparent",border:`2px solid ${color}`,color,borderRadius:10,fontSize:14,fontWeight:700,cursor:"pointer",transition:"all 0.2s"}} onMouseEnter={e=>e.target.style.background=color+"20"} onMouseLeave={e=>e.target.style.background="transparent"}>{label}</button>))}</div>
      <div style={{maxWidth:500,margin:"16px auto 0",display:"flex",gap:10,justifyContent:"center"}}><button onClick={shuffle} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>🔀 Shuffle</button><button onClick={reset} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>↺ Reset</button></div>
      <div style={{textAlign:"center",color:"#444",fontSize:11,marginTop:16}}>Space = flip · ← = review · → = got it</div>
    </div>);
}
