"use client";
import { useState, useCallback, useEffect } from "react";
const GOLD="#D4A843",BLACK="#0D0D0D",CHARCOAL="#1A1A1A",GREEN="#2ECC71",RED_C="#E74C3C";

const CARDS=[
  {front:"What are the four pillars of a trading thesis?",back:"1) Charting Basics (hammers, shooters, dojis, strong candles, CCRP). 2) Technical Analysis (trends, broadening, supply/demand, gaps). 3) Market Structure (BOS/MSS, liquidity, OTE). 4) #TheStrat (scenarios, combos, participation groups, FTFC)."},
  {front:"What is a confluence?",back:"A confluence is when multiple signals from different pillars and/or timeframes line up in the same direction on the same chart. More confluences = higher probability trade. Single signals are coin flips — stacks are edge."},
  {front:"What's the minimum number of confluences for a tradable setup?",back:"Roughly: 3+ confluences = tradable. 5+ = strong. 10+ = high-conviction. Fewer than 3 is a setup you should pass on. The $XLY example had 10 confluences across three pillars before even checking the daily."},
  {front:"How do you build a confluence checklist?",back:"1) Pull up a ticker with multiple timeframes (D, W, 2W, 3W, monthly). 2) Go through each pillar — what bullish/bearish signals do you see? 3) Write each signal with the TF it appears on. 4) Check for multi-TF alignment. 5) Check for target alignment (one TF's target = another TF's entry)."},
  {front:"What is an 'anchor pillar'?",back:"The pillar that resonates most with you — the one you see first when you look at a chart. Adex sees Strat combos first. Abi sees market structure first. Everyone has a natural anchor. Use it as your starting point, but then confirm across the other three pillars."},
  {front:"Why isn't your anchor pillar enough on its own?",back:"Because a single signal is a coin flip. A hammer alone isn't enough. A 2-1-2u alone isn't enough. Your anchor gets you to the chart, but you need the other three pillars and multiple timeframes to confirm the thesis before trading."},
  {front:"What 10 bullish confluences did $XLY have in the case study?",back:"1) 1-3 on the weekly. 2) FTFC green. 3) Strong candle close. 4) Inside 2W hammer. 5) Potential 2-1-2u on 2W. 6) Liquidity sweep. 7) OTE holding. 8) Inside 3W. 9) CCRP on 3W. 10) Potential 2-1-2u on 3W. All before even checking the daily."},
  {front:"Why is timeframe target alignment important?",back:"When one TF's target matches another TF's entry, it creates a domino effect. $XLY's weekly target (204.49) was the same as the 2W target. When both triggered, the 3W CCRP completed. Aligned targets multiply conviction because multiple participation groups all confirm the same destination."},
  {front:"What does it mean to 'choose your participant timeframe'?",back:"Deciding which TF participant you are BEFORE entering. A daily participant holds hours to days. A weekly participant holds up to a week. A 3W participant holds up to 3 weeks. Your participant level defines your invalidation, holding period, and target."},
  {front:"Why do you need to know your participant timeframe?",back:"Because pullbacks are normal. If you're a 3W participant and price dips on day 3, you don't panic — you have up to 3 weeks for the setup to play out. Without knowing your participant, you'll exit on normal wicks and miss the move."},
  {front:"What is the trade-off between higher and lower TF participants?",back:"Higher TF participants = larger magnitude targets but more patience required. Lower TF participants = faster moves but smaller targets. Neither is objectively better — match your participant to the setup's timeframe and your personality."},
  {front:"Can you upgrade your participant mid-trade?",back:"Yes. In the $XLY example, a weekly participant could have noticed the 3W CCRP developing and upgraded to a 3W participant — holding longer, rolling contracts, or buying more time. Higher participant = higher target potential if higher-TF signals confirm."},
  {front:"On $XLY day 3, price pulled back. Should a 3-week participant have exited?",back:"No. A 3W participant's invalidation is a candle CLOSE below the inside bar on the 3W timeframe. A day 3 pullback is normal noise. As long as the weekly/2W/3W setup hasn't invalidated, the thesis is intact. Panic-exiting on wicks is the #1 way to miss winners."},
  {front:"What do wicks through invalidation mean?",back:"Nothing — wicks do NOT invalidate a setup. Only a candle CLOSE beyond the invalidation level counts. Wicks are normal; they're often liquidity sweeps. Wait for the candle to close before making any exit decision."},
  {front:"How does the 'if-then' framework work for building a thesis?",back:"'IF price triggers the weekly 1-3-2u, THEN the target is the prior candle's high.' 'IF price hits that target, THEN the 2W 2-1-2u triggers.' Stack if-thens across timeframes to map the pathway from entry to highest target."},
  {front:"What role do gap fills play in confluence building?",back:"Gap fills act as magnets for price. If a gap aligns with your directional thesis, it becomes an additional confluence. $XLY had a gap fill to the upside that aligned with the weekly and 2W targets — adding another layer of conviction."},
  {front:"What does it mean for an OTE to 'hold' on a higher timeframe?",back:"Price may wick below the 0.786 on a lower TF but not close below on a higher TF. In $XLY, the weekly wicked the 0.886 area but the 2W chart clearly showed those wicks holding the 0.786. Always check higher TFs for confirmation of OTE."},
  {front:"What's the proper trading workflow (8 steps)?",back:"1) Scan multiple TFs. 2) Anchor — what jumps out? 3) Expand — check other pillars. 4) Align — do TFs agree? 5) Count confluences. 6) Choose participant TF. 7) Enter on trigger in force. 8) Manage until target or candle close invalidation."},
  {front:"Why did the $XLY trade play out exactly as predicted?",back:"Because 10 confluences across multiple timeframes all pointed to the same destination. When the weekly 1-3-2u triggered, it hit the 2W target. The 2W trigger hit the 3W CCRP. Every confluence on the checklist played out in sequence. That's the power of stacking signals."},
  {front:"What's the one rule about analyzing charts that ties everything together?",back:"You can't do your analysis based on just one thing. Use your anchor pillar as the starting point, but look at other charts, other timeframes, and other pillars to find more confluences. Multi-pillar, multi-timeframe confirmation is what creates edge."},
];

export default function Flashcards(){
  const[deck,setDeck]=useState([...CARDS]);const[idx,setIdx]=useState(0);const[flipped,setFlipped]=useState(false);
  const[known,setKnown]=useState(new Set());const[reviewing,setReviewing]=useState(new Set());const[animDir,setAnimDir]=useState(null);
  const current=deck[idx];const total=deck.length;const progress=((known.size+reviewing.size)/CARDS.length)*100;
  const flip=useCallback(()=>setFlipped(f=>!f),[]);
  const next=useCallback((st)=>{const id=deck[idx].front;if(st==="known"){setKnown(p=>new Set([...p,id]));setReviewing(p=>{const n=new Set(p);n.delete(id);return n;});}else{setReviewing(p=>new Set([...p,id]));setKnown(p=>{const n=new Set(p);n.delete(id);return n;});}setAnimDir(st==="known"?"right":"left");setTimeout(()=>{setFlipped(false);setAnimDir(null);setIdx(i=>(i+1)%total);},250);},[deck,idx,total]);
  const shuffle=useCallback(()=>{setDeck([...CARDS].sort(()=>Math.random()-0.5));setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  const reset=useCallback(()=>{setDeck([...CARDS]);setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  useEffect(()=>{const h=(e)=>{if(e.code==="Space"){e.preventDefault();flip();}if(e.code==="ArrowRight")next("known");if(e.code==="ArrowLeft")next("review");};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h);},[flip,next]);
  return(
    <div style={{minHeight:"100vh",background:`linear-gradient(135deg,${BLACK} 0%,#1a1510 100%)`,fontFamily:"'Segoe UI',system-ui,sans-serif",padding:"20px",boxSizing:"border-box"}}>
      <div style={{textAlign:"center",marginBottom:20}}><div style={{color:GOLD,fontSize:11,letterSpacing:3,fontWeight:700,marginBottom:4}}>ADEXTRADES UNIVERSITY</div><div style={{color:"#fff",fontSize:22,fontWeight:700}}>Lesson #8 Flashcards</div><div style={{color:"#888",fontSize:13,marginTop:2}}>Putting It All Together</div></div>
      <div style={{maxWidth:500,margin:"0 auto 16px",display:"flex",gap:12,alignItems:"center"}}><div style={{flex:1,height:6,background:"#2a2a2a",borderRadius:3,overflow:"hidden"}}><div style={{height:"100%",width:`${progress}%`,background:`linear-gradient(90deg,${GOLD},#e8c85a)`,borderRadius:3,transition:"width 0.4s"}}/></div><div style={{color:"#888",fontSize:12,whiteSpace:"nowrap"}}>{known.size+reviewing.size}/{CARDS.length}</div></div>
      <div style={{maxWidth:500,margin:"0 auto 20px",display:"flex",justifyContent:"center",gap:20}}>{[{c:GREEN,l:"Mastered",v:known.size},{c:RED_C,l:"Review",v:reviewing.size},{c:"#555",l:"Unseen",v:CARDS.length-known.size-reviewing.size}].map(({c,l,v})=>(<div key={l} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:8,height:8,borderRadius:"50%",background:c}}/><span style={{color:"#aaa",fontSize:12}}>{l}: {v}</span></div>))}</div>
      <div style={{maxWidth:500,margin:"0 auto",perspective:1000}}>
        <div onClick={flip} style={{cursor:"pointer",position:"relative",height:320,transformStyle:"preserve-3d",transition:animDir?"transform 0.25s, opacity 0.25s":"transform 0.5s",transform:`${flipped?"rotateY(180deg)":"rotateY(0)"} ${animDir==="right"?"translateX(60px)":animDir==="left"?"translateX(-60px)":""}`,opacity:animDir?0.3:1}}>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",background:`linear-gradient(145deg,${CHARCOAL},#222)`,border:`2px solid ${GOLD}40`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"30px 28px",boxSizing:"border-box"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:16,opacity:0.7}}>QUESTION</div><div style={{color:"#fff",fontSize:17,textAlign:"center",lineHeight:1.5,fontWeight:500}}>{current.front}</div><div style={{color:"#666",fontSize:11,marginTop:"auto",paddingTop:12}}>Tap to flip</div></div>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",transform:"rotateY(180deg)",background:`linear-gradient(145deg,#1a1508,#1e1a10)`,border:`2px solid ${GOLD}`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"22px 26px",boxSizing:"border-box",overflow:"auto"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:10}}>ANSWER</div><div style={{color:"#e8e0d0",fontSize:13,textAlign:"center",lineHeight:1.6}}>{current.back}</div></div>
        </div>
      </div>
      <div style={{textAlign:"center",color:"#666",fontSize:12,margin:"12px 0"}}>Card {idx+1} of {total}</div>
      <div style={{maxWidth:500,margin:"0 auto",display:"flex",gap:12,justifyContent:"center"}}>{[{label:"← Review Again",color:RED_C,action:"review"},{label:"Got It →",color:GREEN,action:"known"}].map(({label,color,action})=>(<button key={action} onClick={()=>next(action)} style={{flex:1,padding:"14px 0",background:"transparent",border:`2px solid ${color}`,color,borderRadius:10,fontSize:14,fontWeight:700,cursor:"pointer",transition:"all 0.2s"}} onMouseEnter={e=>e.target.style.background=color+"20"} onMouseLeave={e=>e.target.style.background="transparent"}>{label}</button>))}</div>
      <div style={{maxWidth:500,margin:"16px auto 0",display:"flex",gap:10,justifyContent:"center"}}><button onClick={shuffle} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>🔀 Shuffle</button><button onClick={reset} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>↺ Reset</button></div>
      <div style={{textAlign:"center",color:"#444",fontSize:11,marginTop:16}}>Space = flip · ← = review · → = got it</div>
    </div>);
}
