"use client";
import { useState, useCallback, useEffect } from "react";
const GOLD="#D4A843",BLACK="#0D0D0D",CHARCOAL="#1A1A1A",GREEN="#2ECC71",RED_C="#E74C3C";

const CARDS=[
  {front:"What are 'the Greeks' in options trading?",back:"A set of measures that describe how an options premium responds to market conditions — changes in the underlying price, time decay, and implied volatility. The three main ones for long options: Delta, Theta, and Gamma."},
  {front:"What is delta?",back:"The rate of change in a contract's premium for a $1 move in the underlying stock. For calls: 0 to 1. For puts: 0 to -1. Example: delta 0.30 means your premium gains $0.30 when the stock gains $1."},
  {front:"Where does delta approach 1 (for a call)?",back:"Deep in-the-money. The deeper ITM a call goes, the more it moves 1:1 with the stock. At delta = 1, it essentially trades like 100 shares."},
  {front:"Where does delta approach 0 (for a call)?",back:"Deep out-of-the-money. A far OTM call barely moves even on big stock moves because the market sees little chance of it finishing ITM."},
  {front:"Stock $AAPL $235 call, premium $2.50, delta 0.30. Stock rises from $229 to $230. What's the new premium?",back:"$2.80. Add delta to the premium: $2.50 + $0.30 = $2.80. Delta is the rate of change per $1 move — just add it to the old premium."},
  {front:"What is theta?",back:"The rate of decay in the premium per day. Theta is ALWAYS negative for long options — time is eating your premium every single day. Assumes the stock price stays constant."},
  {front:"Why does theta accelerate in the last 30 days before expiration?",back:"Because extrinsic (time) value decays exponentially near expiration. There's less time for anything to happen, so the market rapidly discounts the 'maybe' premium it was paying. Inside 30 DTE, theta gets aggressive."},
  {front:"Stock $AAPL $235 call, premium $2.50, theta -$0.25. One day passes, stock still at $229. New premium?",back:"$2.25. Subtract theta: $2.50 − $0.25 = $2.25. If the stock doesn't move, you lose the theta amount every day."},
  {front:"What's the Delta-Theta Ratio rule?",back:"Delta must be AT LEAST 2× Theta. A 2:1 ratio is the minimum acceptable. 3:1 or 4:1 is much better. If theta exceeds delta, every day that passes costs you more than a $1 move gains — you're fighting the Greeks."},
  {front:"Why is a delta of 0.35 with theta of -0.52 a BAD contract?",back:"Because theta exceeds delta (ratio is roughly 0.67:1). You need the stock to move $2 just to break even on one day of theta decay. The Greeks themselves are fighting against you — that's a statistically unprofitable contract."},
  {front:"Why are weekly contracts often called 'unprofitable'?",back:"Because their theta is frequently 2-3× their delta, meaning the Greeks are structurally fighting the holder. Institutions SELL weeklies to retail precisely because the Greeks favor the seller. Not impossible to win — but statistically uphill."},
  {front:"What is gamma?",back:"The rate of change in delta. Gamma is to delta what acceleration is to speed. It tells you how fast your delta is changing as the stock moves. Higher gamma = more explosive premium changes."},
  {front:"Delta = speed, Gamma = ?",back:"Acceleration. If delta tells you how fast your premium is moving, gamma tells you how fast your delta is changing. Press the gas pedal (stock moves) and gamma determines the acceleration of your premium gains."},
  {front:"Stock $AAPL $235 call, premium $2.50, delta 0.30, gamma 0.10. Stock moves from $229 to $230. What's the new premium?",back:"$2.90. First add gamma to delta: 0.30 + 0.10 = 0.40. Then add that to the premium: $2.50 + $0.40 = $2.90. Gamma is why profits accelerate as price approaches your strike."},
  {front:"When is gamma highest?",back:"At-the-money (ATM) and close to expiration. ATM because the contract is on the edge of ITM/OTM — any $1 move matters enormously. Close to expiration because uncertainty collapses and every small move radically changes the probability."},
  {front:"When is gamma lowest?",back:"Far from expiration, and deep ITM or deep OTM. Far from expiration because uncertainty is high and small moves don't matter much. Deep ITM/OTM because direction is 'decided' and small moves don't change the outcome."},
  {front:"Why does your contract 'explode' as price approaches your strike?",back:"Gamma. Each incremental $1 move adds to your delta (which accelerates premium gains), which adds more delta again. That's why you can be -50% on a swing and then jump to -30% to +10% in minutes as price closes in on the strike. Exponential profit curve."},
  {front:"How much time should you buy relative to your thesis timeframe?",back:"2 to 4× your thesis timeframe. Daily thesis → 2-4 days (prefer 1-2 weeks). Weekly thesis → 2-4 weeks. Monthly thesis → 2-4 months. Buy enough time so theta doesn't kill you if the setup needs to breathe."},
  {front:"You have a weekly thesis. What's the minimum expiration you should buy?",back:"2 weeks out. Ideally 4-6 weeks. The rule: at least 2-4× your thesis timeframe. A weekly setup takes up to a week to play out, so you need buffer for theta."},
  {front:"What does it mean to 'roll' a contract?",back:"Closing your current contract and opening a new one further out in time. You roll when your setup needs more time than your current expiration gives you — if price is consolidating and theta is bleeding you, rolling buys you more time to let the trade play out."},
  {front:"What's the ASAP method for picking a strike?",back:"At-the-Money or In-the-Money contracts. Higher delta, less theta decay, more intrinsic value, higher probability — but more expensive and lower % gains. Use when you're not 100% sure price will hit your target."},
  {front:"What's the Price Target method for picking a strike?",back:"Out-of-the-Money contracts, near your target price. Cheaper, higher % potential, great for explosive days — but no intrinsic value, theta works against you, and needs a big move to profit. Use when you have high conviction in a specific target."},
  {front:"Higher percentage gain always means more money. True or false?",back:"FALSE. A 15% gain on a $4 contract = $60 per contract. A 100% gain on a $0.50 contract = $50 per contract. The higher-$ contract often makes you more money despite the lower %. Don't let % screenshots fool you — dollar gains are what matter."},
  {front:"Adex sees $UPS needs to drop $3 to hit the monthly target but isn't sure it'll get there. ATM or OTM?",back:"ATM (ASAP method). He bought $85 puts while $UPS was at $85.29. Even a partial drop ($85 → $84) gains him dollar-for-dollar on delta. No need for the exact target to be hit to profit. Safer when target is uncertain."},
  {front:"Adex sees $WMT has a clean gap fill at $100 with high conviction. $WMT is at $97. ATM or OTM?",back:"Slightly OTM (Price Target method). He bought $100 calls right at the gap fill target. If price hits $100, those OTM contracts explode in value. Best when you have a clear, high-conviction target."},
  {front:"What is Implied Volatility (IV)?",back:"The market's expectation of future price movement on a stock. High IV = market expects big moves. Low IV = market expects quiet. IV directly inflates options premiums — higher IV means more expensive contracts."},
  {front:"What's 'IV crush'?",back:"The rapid collapse of implied volatility after a catalyst (like earnings). Pre-earnings IV can hit 100%+. After the event, IV crashes back to 20-40%. Even if you're directionally right, the IV drop alone can cut your premium in half. Avoid buying into inflated IV unless you understand this risk."},
  {front:"What's the normal IV range for a liquid stock?",back:"20% to 40%. Anything much above that (100%+) is typically earnings IV or event-driven inflation. Normal setups with IV in the 20-40% range give you predictable premium behavior without IV crush risk."},
];

export default function Flashcards(){
  const[deck,setDeck]=useState([...CARDS]);const[idx,setIdx]=useState(0);const[flipped,setFlipped]=useState(false);
  const[known,setKnown]=useState(new Set());const[reviewing,setReviewing]=useState(new Set());const[animDir,setAnimDir]=useState(null);
  const current=deck[idx];const total=deck.length;const progress=((known.size+reviewing.size)/CARDS.length)*100;
  const flip=useCallback(()=>setFlipped(f=>!f),[]);
  const next=useCallback((st)=>{const id=deck[idx].front;if(st==="known"){setKnown(p=>new Set([...p,id]));setReviewing(p=>{const n=new Set(p);n.delete(id);return n;});setAnimDir("right");setTimeout(()=>{setFlipped(false);setAnimDir(null);setDeck(prev=>{const nd=[...prev];nd.splice(idx,1);return nd.length?nd:prev;});setIdx(i=>i>=deck.length-1?0:i);},250);}else{setReviewing(p=>new Set([...p,id]));setKnown(p=>{const n=new Set(p);n.delete(id);return n;});setAnimDir("left");setTimeout(()=>{setFlipped(false);setAnimDir(null);setDeck(prev=>{const nd=[...prev];const card=nd.splice(idx,1)[0];nd.push(card);return nd;});setIdx(i=>i>=deck.length-1?0:i);},250);}},[deck,idx]);
  const shuffle=useCallback(()=>{setDeck([...CARDS].sort(()=>Math.random()-0.5));setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  const reset=useCallback(()=>{setDeck([...CARDS]);setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  useEffect(()=>{const h=(e)=>{if(e.code==="Space"){e.preventDefault();flip();}if(e.code==="ArrowRight")next("known");if(e.code==="ArrowLeft")next("review");};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h);},[flip,next]);
  return(
    <div style={{minHeight:"100vh",background:`linear-gradient(135deg,${BLACK} 0%,#1a1510 100%)`,fontFamily:"'Segoe UI',system-ui,sans-serif",padding:"20px",boxSizing:"border-box"}}>
      <div style={{textAlign:"center",marginBottom:20}}><div style={{color:GOLD,fontSize:11,letterSpacing:3,fontWeight:700,marginBottom:4}}>ADEXTRADES UNIVERSITY</div><div style={{color:"#fff",fontSize:22,fontWeight:700}}>Lesson #13 Flashcards</div><div style={{color:"#888",fontSize:13,marginTop:2}}>The Right Contract</div></div>
      <div style={{maxWidth:500,margin:"0 auto 16px",display:"flex",gap:12,alignItems:"center"}}><div style={{flex:1,height:6,background:"#2a2a2a",borderRadius:3,overflow:"hidden"}}><div style={{height:"100%",width:`${progress}%`,background:`linear-gradient(90deg,${GOLD},#e8c85a)`,borderRadius:3,transition:"width 0.4s"}}/></div><div style={{color:"#888",fontSize:12,whiteSpace:"nowrap"}}>{known.size+reviewing.size}/{CARDS.length}</div></div>
      <div style={{maxWidth:500,margin:"0 auto 20px",display:"flex",justifyContent:"center",gap:20}}>{[{c:GREEN,l:"Mastered",v:known.size},{c:RED_C,l:"Review",v:reviewing.size},{c:"#555",l:"Unseen",v:CARDS.length-known.size-reviewing.size}].map(({c,l,v})=>(<div key={l} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:8,height:8,borderRadius:"50%",background:c}}/><span style={{color:"#aaa",fontSize:12}}>{l}: {v}</span></div>))}</div>
      <div style={{maxWidth:500,margin:"0 auto",perspective:1000}}>
        <div onClick={flip} style={{cursor:"pointer",position:"relative",height:320,transformStyle:"preserve-3d",transition:animDir?"transform 0.25s, opacity 0.25s":"transform 0.5s",transform:`${flipped?"rotateY(180deg)":"rotateY(0)"} ${animDir==="right"?"translateX(60px)":animDir==="left"?"translateX(-60px)":""}`,opacity:animDir?0.3:1}}>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",background:`linear-gradient(145deg,${CHARCOAL},#222)`,border:`2px solid ${GOLD}40`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"30px 28px",boxSizing:"border-box"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:16,opacity:0.7}}>QUESTION</div><div style={{color:"#fff",fontSize:17,textAlign:"center",lineHeight:1.5,fontWeight:500}}>{current.front}</div><div style={{color:"#666",fontSize:11,marginTop:"auto",paddingTop:12}}>Tap to flip</div></div>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",transform:"rotateY(180deg)",background:`linear-gradient(145deg,#1a1508,#1e1a10)`,border:`2px solid ${GOLD}`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"22px 26px",boxSizing:"border-box",overflow:"auto"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:10}}>ANSWER</div><div style={{color:"#e8e0d0",fontSize:13,textAlign:"center",lineHeight:1.6}}>{current.back}</div></div>
        </div>
      </div>
      <div style={{textAlign:"center",color:"#666",fontSize:12,margin:"12px 0"}}>Card {idx+1} of {total}</div>
      <div style={{maxWidth:500,margin:"0 auto",display:"flex",gap:12,justifyContent:"center"}}>{[{label:"← Review Again",color:RED_C,action:"review"},{label:"Got It →",color:GREEN,action:"known"}].map(({label,color,action})=>(<button key={action} onClick={()=>next(action)} style={{flex:1,padding:"14px 0",background:"transparent",border:`2px solid ${color}`,color,borderRadius:10,fontSize:14,fontWeight:700,cursor:"pointer",transition:"all 0.2s"}} onMouseEnter={e=>e.target.style.background=color+"20"} onMouseLeave={e=>e.target.style.background="transparent"}>{label}</button>))}</div>
      <div style={{maxWidth:500,margin:"16px auto 0",display:"flex",gap:10,justifyContent:"center"}}><button onClick={shuffle} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>🔀 Shuffle</button><button onClick={reset} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>↺ Reset</button></div>
      <div style={{textAlign:"center",color:"#444",fontSize:11,marginTop:16}}>Space = flip · ← = review · → = got it</div>
    </div>);
}
