"use client";
import { useState, useCallback, useEffect } from "react";
const GOLD="#D4A843",BLACK="#0D0D0D",CHARCOAL="#1A1A1A",GREEN="#2ECC71",RED_C="#E74C3C",CG="#26A65B",CR="#E74C3C";

const CARDS=[
  {front:"What is #TheStrat?",back:"A price action trading strategy developed by Rob Smith. It eliminates subjectivity and market noise — it only focuses on price action. Every scenario is empirical and indisputable."},
  {front:"What are the four universal truths of price action?",back:"1) Price can only move in three ways (scenarios 1, 2, 3). 2) We enter trades based on actionable signals. 3) We determine aggression via timeframe continuity. 4) Price expands over time creating broadening formations."},
  {front:"What is a Scenario 1 (Inside Bar)?",back:"A candle with a LOWER HIGH and HIGHER LOW compared to the previous candle. Price stays inside the previous range. It represents consolidation, indecision, or equilibrium. Action: WAIT for the next candle to break one side."},
  {front:"What is a Scenario 2 (Directional Candle)?",back:"A candle that breaks ONE side of the previous candle. 2u = breaks only the high (bullish). 2d = breaks only the low (bearish). Shows clear directional movement — you know who has control."},
  {front:"Does the color of the candle matter for Strat scenarios?",back:"No. A green candle that breaks the low of the previous bar is still a 2d. The scenario is determined by PRICE relative to the previous candle, not by candle color. This is what makes #TheStrat objective and non-subjective."},
  {front:"What is a Scenario 3 (Outside Bar)?",back:"A candle that breaks BOTH the high AND the low of the previous candle. Shows aggression by one side. A 3 cannot form without first being a 2. The secondary side (which broke last) typically shows the most aggression."},
  {front:"Why is a scenario 3 a broadening formation on a lower timeframe?",back:"A 3 bar creates a higher high AND a lower low vs. the previous candle — that's the definition of a broadening formation. If you zoom into a lower timeframe, you'll see the expanding range (megaphone) that formed within that candle."},
  {front:"Can a scenario 3 form without first being a scenario 2?",back:"No. A 3 must be a 2 first. Example: candle opens, breaks the high (becomes 2u), then sellers overpower and also break the low (becomes 3). The secondary side that broke last typically shows the most aggression."},
  {front:"How do you determine a candle's Strat scenario?",back:"Always compare to the PREVIOUS candle (look left). Does it break neither side (1)? One side (2u or 2d)? Both sides (3)? The scenario is always in relation to the candle to the left."},
  {front:"What are participation groups?",back:"Each timeframe represents a different group of participants. Daily candle = participants who acted that day. Weekly = that week. Monthly = that month. This determines HOW LONG a trade can take to play out."},
  {front:"A 4-week shooter triggers 2d on week 1 but pulls back on week 2. Is the setup invalidated?",back:"Not necessarily. A 4-week participant has up to 4 weeks for the move to play out. Week 1 trigger + week 2 pullback is normal — the setup isn't invalidated until the timeframe period expires or the trigger fails."},
  {front:"What is Full Timeframe Continuity (FTFC)?",back:"When ALL timeframes (D, W, M, Q, Y) are aligned in the same direction — all trading above their opens (bullish) or all below (bearish). FTFC signals strong institutional momentum and highest probability of continuation."},
  {front:"Price is trading above the open on D, W, M, Q, and Y. What does this mean?",back:"Bullish FTFC — institutions are buying. You want to be in calls/long. This is the highest probability environment for bullish trades because every participation group is aligned to the upside."},
  {front:"What are the four actionable signals in #TheStrat?",back:"1) Inside bar breakout. 2) Hammer (after downtrend, wait for next candle above high). 3) Shooter (after uptrend, wait for next candle below low). 4) Rev strat (reversal of inside bar breakout)."},
  {front:"When do you enter an inside bar breakout trade?",back:"Wait for the NEXT candle to open and break the high or low of the inside bar. Enter when it breaks IN FORCE (with strength, not just wicking the level). You do NOT trade the inside bar itself."},
  {front:"A hammer forms on the weekly chart. When do you enter?",back:"Do NOT trade the hammer. Wait for the NEXT WEEK'S candle to open and trade ABOVE the hammer's high. That is your entry signal. If the next week gaps down below the hammer, there is no entry."},
  {front:"What is a Rev Strat?",back:"A reversal of the inside bar breakout. Inside bar forms → next candle breaks one side (e.g., 2d) → breakout FAILS → price reverses through the opposite side of the inside bar. It's a universal truth: the reversal of equilibrium cannot be disputed."},
  {front:"When does a Rev Strat become high probability?",back:"When price crosses above 50% of the inside bar (for a bullish rev strat). At that point, there's a higher probability of taking out the high of the inside bar. You can flip from puts to calls."},
  {front:"What does 'in force' mean for actionable signals?",back:"The trigger is breaking the level with STRENGTH — price is not looking back. It's pushing through decisively, not just wicking the level and reversing. You want the breakout to be convincing before entering."},
  {front:"Why does the relay race analogy apply to timeframes?",back:"Timeframes pass the baton like relay race legs. The daily triggers a weekly Strat combo. The weekly passes to the monthly. When multiple timeframes trigger in sequence, the probability of continuation increases. This is why we look at combinations."},
];

export default function Flashcards(){
  const[deck,setDeck]=useState([...CARDS]);const[idx,setIdx]=useState(0);const[flipped,setFlipped]=useState(false);
  const[known,setKnown]=useState(new Set());const[reviewing,setReviewing]=useState(new Set());const[animDir,setAnimDir]=useState(null);
  const current=deck[idx];const total=deck.length;const progress=((known.size+reviewing.size)/CARDS.length)*100;
  const flip=useCallback(()=>setFlipped(f=>!f),[]);
  const next=useCallback((status)=>{const id=deck[idx].front;if(status==="known"){setKnown(p=>new Set([...p,id]));setReviewing(p=>{const n=new Set(p);n.delete(id);return n;});setAnimDir("right");setTimeout(()=>{setFlipped(false);setAnimDir(null);setDeck(prev=>{const nd=[...prev];nd.splice(idx,1);return nd.length?nd:prev;});setIdx(i=>i>=deck.length-1?0:i);},250);}else{setReviewing(p=>new Set([...p,id]));setKnown(p=>{const n=new Set(p);n.delete(id);return n;});setAnimDir("left");setTimeout(()=>{setFlipped(false);setAnimDir(null);setDeck(prev=>{const nd=[...prev];const card=nd.splice(idx,1)[0];nd.push(card);return nd;});setIdx(i=>i>=deck.length-1?0:i);},250);}},[deck,idx]);
  const shuffle=useCallback(()=>{setDeck([...CARDS].sort(()=>Math.random()-0.5));setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  const reset=useCallback(()=>{setDeck([...CARDS]);setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  useEffect(()=>{const h=(e)=>{if(e.code==="Space"){e.preventDefault();flip();}if(e.code==="ArrowRight")next("known");if(e.code==="ArrowLeft")next("review");};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h);},[flip,next]);
  return(
    <div style={{minHeight:"100vh",background:`linear-gradient(135deg,${BLACK} 0%,#1a1510 100%)`,fontFamily:"'Segoe UI',system-ui,sans-serif",padding:"20px",boxSizing:"border-box"}}>
      <div style={{textAlign:"center",marginBottom:20}}><div style={{color:GOLD,fontSize:11,letterSpacing:3,fontWeight:700,marginBottom:4}}>ADEXTRADES UNIVERSITY</div><div style={{color:"#fff",fontSize:22,fontWeight:700}}>Lesson #6 Flashcards</div><div style={{color:"#888",fontSize:13,marginTop:2}}>Introducing: #TheStrat</div></div>
      <div style={{maxWidth:500,margin:"0 auto 16px",display:"flex",gap:12,alignItems:"center"}}><div style={{flex:1,height:6,background:"#2a2a2a",borderRadius:3,overflow:"hidden"}}><div style={{height:"100%",width:`${progress}%`,background:`linear-gradient(90deg,${GOLD},#e8c85a)`,borderRadius:3,transition:"width 0.4s"}}/></div><div style={{color:"#888",fontSize:12,whiteSpace:"nowrap"}}>{known.size+reviewing.size}/{CARDS.length}</div></div>
      <div style={{maxWidth:500,margin:"0 auto 20px",display:"flex",justifyContent:"center",gap:20}}>{[{c:GREEN,l:"Mastered",v:known.size},{c:RED_C,l:"Review",v:reviewing.size},{c:"#555",l:"Unseen",v:CARDS.length-known.size-reviewing.size}].map(({c,l,v})=>(<div key={l} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:8,height:8,borderRadius:"50%",background:c}}/><span style={{color:"#aaa",fontSize:12}}>{l}: {v}</span></div>))}</div>
      <div style={{maxWidth:500,margin:"0 auto",perspective:1000}}>
        <div onClick={flip} style={{cursor:"pointer",position:"relative",height:320,transformStyle:"preserve-3d",transition:animDir?"transform 0.25s, opacity 0.25s":"transform 0.5s",transform:`${flipped?"rotateY(180deg)":"rotateY(0)"} ${animDir==="right"?"translateX(60px)":animDir==="left"?"translateX(-60px)":""}`,opacity:animDir?0.3:1}}>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",background:`linear-gradient(145deg,${CHARCOAL},#222)`,border:`2px solid ${GOLD}40`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"30px 28px",boxSizing:"border-box"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:16,opacity:0.7}}>QUESTION</div><div style={{color:"#fff",fontSize:17,textAlign:"center",lineHeight:1.5,fontWeight:500}}>{current.front}</div><div style={{color:"#666",fontSize:11,marginTop:"auto",paddingTop:12}}>Tap to flip</div></div>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",transform:"rotateY(180deg)",background:`linear-gradient(145deg,#1a1508,#1e1a10)`,border:`2px solid ${GOLD}`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"24px 28px",boxSizing:"border-box",overflow:"auto"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:12}}>ANSWER</div><div style={{color:"#e8e0d0",fontSize:14,textAlign:"center",lineHeight:1.6}}>{current.back}</div></div>
        </div>
      </div>
      <div style={{textAlign:"center",color:"#666",fontSize:12,margin:"12px 0"}}>Card {idx+1} of {total}</div>
      <div style={{maxWidth:500,margin:"0 auto",display:"flex",gap:12,justifyContent:"center"}}>{[{label:"← Review Again",color:RED_C,action:"review"},{label:"Got It →",color:GREEN,action:"known"}].map(({label,color,action})=>(<button key={action} onClick={()=>next(action)} style={{flex:1,padding:"14px 0",background:"transparent",border:`2px solid ${color}`,color,borderRadius:10,fontSize:14,fontWeight:700,cursor:"pointer",transition:"all 0.2s"}} onMouseEnter={e=>e.target.style.background=color+"20"} onMouseLeave={e=>e.target.style.background="transparent"}>{label}</button>))}</div>
      <div style={{maxWidth:500,margin:"16px auto 0",display:"flex",gap:10,justifyContent:"center"}}><button onClick={shuffle} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>🔀 Shuffle</button><button onClick={reset} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>↺ Reset</button></div>
      <div style={{textAlign:"center",color:"#444",fontSize:11,marginTop:16}}>Space = flip · ← = review · → = got it</div>
    </div>);
}
