"use client";
import { useState, useCallback, useEffect } from "react";
const GOLD="#D4A843",BLACK="#0D0D0D",CHARCOAL="#1A1A1A",GREEN="#2ECC71",RED_C="#E74C3C";
const CARDS=[
  {front:"What is the universal target rule for all Strat combos?",back:"Break a high → target = prior candle's HIGH. Break a low → target = prior candle's LOW. Always look left. If the prior candle's level is already surpassed, look one more candle to the left."},
  {front:"What is a 2-1-2u setup?",back:"A directional candle (2), followed by an inside bar (1), followed by a directional candle breaking the upside (2u). Entry = high of the inside bar. Target = high of the preceding candle. Can be a reversal (2d-1-2u) or continuation (2u-1-2u)."},
  {front:"What is a 2-1-2d setup?",back:"Same structure but bearish: directional candle (2), inside bar (1), directional candle breaking the downside (2d). Entry = low of the inside bar. Target = low of the preceding candle."},
  {front:"Is the entry different for a 2-1-2 reversal vs. a 2-1-2 continuation?",back:"No — the entry and target mechanics are IDENTICAL. Entry = break of the inside bar. Target = prior candle's high or low. Whether it's a reversal or continuation doesn't change how you trade it."},
  {front:"What is a 3-1-2 setup?",back:"Same as a 2-1-2 but the first candle is a scenario 3 (outside bar). Entry = break of the inside bar. Target = the 3 bar's high (for 3-1-2u) or low (for 3-1-2d). The target is further because 3 bars have wider ranges."},
  {front:"How do you trade the 1-3 Rev Strat?",back:"Inside bar forms → next candle breaks one side (e.g., 2d) → breakout fails → price reverses past 50% of the inside bar. Entry at 50%. Target 1 = high of inside bar. Target 2 = high of prior candle (look left)."},
  {front:"What is the 1-3-2 setup?",back:"After a 1-3 (inside bar + outside bar) forms, wait for the NEXT candle to trigger directionally off the 3 bar. If it triggers 2u, enter long. Target = look left (if inside bar's high is already below entry, look one more candle left). Invalidation = opposite side of the 3 bar."},
  {front:"What is inside bar consolidation (double/triple/quadruple inside)?",back:"Multiple consecutive inside bars stacking up = increasing consolidation. Traded same as regular inside bar breakout. The coiled spring effect: # of inside bars = potential # of extension candles in the breakout direction."},
  {front:"Why is inside bar consolidation like a coiled spring?",back:"The longer price consolidates (more inside bars), the more potential energy builds. When the breakout happens, it often results in an explosive move — like releasing a compressed spring. Triple inside = potential for 3 extension candles."},
  {front:"What is the invalidation for a 2-1-2u setup?",back:"A candle CLOSE below the inside bar's low (the opposite side). A wick alone does NOT invalidate — only a candle close. 'The reason you enter is the reason you exit' — the 2-1-2u is invalidated by a 2-1-2d."},
  {front:"'The reason you enter is the reason you exit.' What does this mean?",back:"If you enter because of a double inside day breakout to the upside, you exit when that setup is invalidated — meaning price must CLOSE below the inside bar to invalidate. Until that happens, your thesis is intact."},
  {front:"Does a wick through invalidation mean you should exit?",back:"No. Only a candle CLOSE beyond invalidation means the setup is invalidated. Wicks through invalidation happen frequently (liquidity sweeps) and price often reverses back. Wait for the candle to close before making a decision."},
  {front:"What is the multi-timeframe relay concept?",back:"One Strat combo's TARGET on a lower timeframe becomes the ENTRY for a combo on a higher timeframe. This creates a domino effect: daily target → 2-day entry → 2-day target → 3-day entry. When multiple TFs trigger in the same direction, confidence stacks."},
  {front:"What is the bus analogy?",back:"The more timeframes 'on the bus' heading in the same direction, the higher your confidence. If 1D, 2D, 3D, 4D, and 5D all have 2-1-2u setups, you have 5 participation groups aligned. Even if the daily consolidates, the 5-day participant has up to 5 days."},
  {front:"How did the $AMGN example demonstrate multi-TF relay?",back:"$AMGN had a double inside day. The daily target was the 2-day entry. The 2-day target was the 3-day entry. Three TFs all pointing up. The daily never closed below invalidation despite wicking it — the thesis stayed intact and price reached the higher TF target."},
  {front:"How did the $WMT example demonstrate the top-down approach?",back:"$WMT had a quarterly hammer → if triggered, target = $105.30. Pathway: 3-1-2u weekly → target triggers 2-1-2u monthly → target triggers quarterly hammer. Each TF passed the baton. The pathway from weekly to quarterly was a chain of Strat triggers."},
  {front:"What is the top-down approach?",back:"Start with the HIGHEST timeframe signal (quarterly/monthly). What setup exists? Then work down: how does the daily trigger the weekly? How does the weekly trigger the monthly? If you see the domino chain, you know the pathway to the highest magnitude target."},
  {front:"What participant are you? Why does this question matter?",back:"Your participant timeframe determines your invalidation level and how long you should hold. A 1-day participant exits if the daily invalidates. A 2-day participant has more leeway. Know your timeframe BEFORE entering — it defines when you exit."},
  {front:"If a triple inside 6-day bar breaks to the upside, how many extension candles can you potentially get?",back:"Potentially 3 extension candles to the upside (one for each inside bar). The key word is POTENTIALLY — not guaranteed. The invalidation is a candle close below the inside bar. As long as that holds, the thesis remains intact."},
  {front:"On the Strat combo cheat sheet, there are ~25 combinations. How many does Adex focus on?",back:"5 core combos: 1) 2-1-2 reversal/continuation, 2) 3-1-2, 3) 1-3 Rev Strat, 4) 1-3-2, 5) Inside bar consolidation (double/triple/quadruple inside). Master these before exploring others."},
];

export default function Flashcards(){
  const[deck,setDeck]=useState([...CARDS]);const[idx,setIdx]=useState(0);const[flipped,setFlipped]=useState(false);
  const[known,setKnown]=useState(new Set());const[reviewing,setReviewing]=useState(new Set());const[animDir,setAnimDir]=useState(null);
  const current=deck[idx];const total=deck.length;const progress=((known.size+reviewing.size)/CARDS.length)*100;
  const flip=useCallback(()=>setFlipped(f=>!f),[]);
  const next=useCallback((st)=>{const id=deck[idx].front;if(st==="known"){setKnown(p=>new Set([...p,id]));setReviewing(p=>{const n=new Set(p);n.delete(id);return n;});setAnimDir("right");setTimeout(()=>{setFlipped(false);setAnimDir(null);setDeck(prev=>{const nd=[...prev];nd.splice(idx,1);return nd.length?nd:prev;});setIdx(i=>i>=deck.length-1?0:i);},250);}else{setReviewing(p=>new Set([...p,id]));setKnown(p=>{const n=new Set(p);n.delete(id);return n;});setAnimDir("left");setTimeout(()=>{setFlipped(false);setAnimDir(null);setDeck(prev=>{const nd=[...prev];const card=nd.splice(idx,1)[0];nd.push(card);return nd;});setIdx(i=>i>=deck.length-1?0:i);},250);}},[deck,idx]);
  const shuffle=useCallback(()=>{setDeck([...CARDS].sort(()=>Math.random()-0.5));setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  const reset=useCallback(()=>{setDeck([...CARDS]);setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  useEffect(()=>{const h=(e)=>{if(e.code==="Space"){e.preventDefault();flip();}if(e.code==="ArrowRight")next("known");if(e.code==="ArrowLeft")next("review");};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h);},[flip,next]);
  return(
    <div style={{minHeight:"100vh",background:`linear-gradient(135deg,${BLACK} 0%,#1a1510 100%)`,fontFamily:"'Segoe UI',system-ui,sans-serif",padding:"20px",boxSizing:"border-box"}}>
      <div style={{textAlign:"center",marginBottom:20}}><div style={{color:GOLD,fontSize:11,letterSpacing:3,fontWeight:700,marginBottom:4}}>ADEXTRADES UNIVERSITY</div><div style={{color:"#fff",fontSize:22,fontWeight:700}}>Lesson #7 Flashcards</div><div style={{color:"#888",fontSize:13,marginTop:2}}>Our Favorite Combos</div></div>
      <div style={{maxWidth:500,margin:"0 auto 16px",display:"flex",gap:12,alignItems:"center"}}><div style={{flex:1,height:6,background:"#2a2a2a",borderRadius:3,overflow:"hidden"}}><div style={{height:"100%",width:`${progress}%`,background:`linear-gradient(90deg,${GOLD},#e8c85a)`,borderRadius:3,transition:"width 0.4s"}}/></div><div style={{color:"#888",fontSize:12,whiteSpace:"nowrap"}}>{known.size+reviewing.size}/{CARDS.length}</div></div>
      <div style={{maxWidth:500,margin:"0 auto 20px",display:"flex",justifyContent:"center",gap:20}}>{[{c:GREEN,l:"Mastered",v:known.size},{c:RED_C,l:"Review",v:reviewing.size},{c:"#555",l:"Unseen",v:CARDS.length-known.size-reviewing.size}].map(({c,l,v})=>(<div key={l} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:8,height:8,borderRadius:"50%",background:c}}/><span style={{color:"#aaa",fontSize:12}}>{l}: {v}</span></div>))}</div>
      <div style={{maxWidth:500,margin:"0 auto",perspective:1000}}>
        <div onClick={flip} style={{cursor:"pointer",position:"relative",height:320,transformStyle:"preserve-3d",transition:animDir?"transform 0.25s, opacity 0.25s":"transform 0.5s",transform:`${flipped?"rotateY(180deg)":"rotateY(0)"} ${animDir==="right"?"translateX(60px)":animDir==="left"?"translateX(-60px)":""}`,opacity:animDir?0.3:1}}>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",background:`linear-gradient(145deg,${CHARCOAL},#222)`,border:`2px solid ${GOLD}40`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"30px 28px",boxSizing:"border-box"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:16,opacity:0.7}}>QUESTION</div><div style={{color:"#fff",fontSize:17,textAlign:"center",lineHeight:1.5,fontWeight:500}}>{current.front}</div><div style={{color:"#666",fontSize:11,marginTop:"auto",paddingTop:12}}>Tap to flip</div></div>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",transform:"rotateY(180deg)",background:`linear-gradient(145deg,#1a1508,#1e1a10)`,border:`2px solid ${GOLD}`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"24px 26px",boxSizing:"border-box",overflow:"auto"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:12}}>ANSWER</div><div style={{color:"#e8e0d0",fontSize:13,textAlign:"center",lineHeight:1.6}}>{current.back}</div></div>
        </div>
      </div>
      <div style={{textAlign:"center",color:"#666",fontSize:12,margin:"12px 0"}}>Card {idx+1} of {total}</div>
      <div style={{maxWidth:500,margin:"0 auto",display:"flex",gap:12,justifyContent:"center"}}>{[{label:"← Review Again",color:RED_C,action:"review"},{label:"Got It →",color:GREEN,action:"known"}].map(({label,color,action})=>(<button key={action} onClick={()=>next(action)} style={{flex:1,padding:"14px 0",background:"transparent",border:`2px solid ${color}`,color,borderRadius:10,fontSize:14,fontWeight:700,cursor:"pointer",transition:"all 0.2s"}} onMouseEnter={e=>e.target.style.background=color+"20"} onMouseLeave={e=>e.target.style.background="transparent"}>{label}</button>))}</div>
      <div style={{maxWidth:500,margin:"16px auto 0",display:"flex",gap:10,justifyContent:"center"}}><button onClick={shuffle} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>🔀 Shuffle</button><button onClick={reset} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>↺ Reset</button></div>
      <div style={{textAlign:"center",color:"#444",fontSize:11,marginTop:16}}>Space = flip · ← = review · → = got it</div>
    </div>);
}
