"use client";
import { useState, useCallback, useEffect } from "react";
const GOLD="#D4A843",BLACK="#0D0D0D",CHARCOAL="#1A1A1A",GREEN="#2ECC71",RED_C="#E74C3C";

const CARDS=[
  {front:"What is Optimal Trade Entry (OTE)?",back:"The area where price is most likely to reverse to continue in the prevailing trend. The most favorable price level to enter a trade within a trending market. Other names: Golden Zone, Golden Pocket, Discount Zone, the 618."},
  {front:"What fib levels define the OTE zone?",back:"Between 0.5 and 0.786 of the retracement leg. The 0.618 sits in the middle and is the most common reversal level (the 'Golden Pocket')."},
  {front:"Why is a pullback entry better than a breakout entry?",back:"Same exit, bigger profit. If you enter at the pullback low and exit at the high, you capture the entire swing. If you enter at the breakout high, you capture only a portion. A pullback entry has a better risk-to-reward ratio — lower entry = more profit on the same exit."},
  {front:"How do you draw fibs in an UPTREND?",back:"From the swing LOW to the swing HIGH. The retracement tool projects the 0.5, 0.618, and 0.786 levels downward from the high. When price pulls back into that 0.5-0.786 zone, you look for long entries."},
  {front:"How do you draw fibs in a DOWNTREND?",back:"From the swing HIGH to the swing LOW. The retracement tool projects the 0.5, 0.618, and 0.786 levels upward from the low. When price bounces back into that 0.5-0.786 zone, you look for short entries."},
  {front:"What three fib levels should you use on your chart?",back:"0.5, 0.618, and 0.786. Skip the rest. These three define the OTE zone and keep the chart clean. You don't need every Fibonacci level — the OTE band is what matters."},
  {front:"What's the 0.618 also called?",back:"The Golden Pocket or Golden Zone. It's the most common reversal level — the single fib line where you'll see the highest frequency of reactions. Some traders wait specifically for the 0.618 tap before taking any setup."},
  {front:"What's the 0.786?",back:"The 'last line of defense.' If price breaks below the 0.618, the 0.786 is your last chance at a reversal. A candle CLOSE below 0.786 invalidates the OTE trade. But many setups DO reverse off 0.786 after breaking 0.618 — don't panic at 0.618."},
  {front:"Does price ALWAYS reverse at 0.618?",back:"No. OTE is a probability zone, not a guarantee. Price can bounce at 0.5, at 0.618, at 0.786, or break below entirely (invalidating the setup). The 0.618 is just the highest-frequency reversal level — not an automatic bounce."},
  {front:"What's a confluence zone?",back:"When multiple fibs overlap — e.g., the 0.618 of one swing lines up near the 0.5 of another swing. These overlapping levels act as stronger support/resistance because multiple retracement paths all converge at the same price area."},
  {front:"Why draw fibs from EVERY swing high, not just the most recent one?",back:"Because price broadens over time. A new swing high can form next week and supersede your current fib. Keeping fibs at multiple defined swing lows/highs lets you spot confluence zones where several retracement levels cluster — the strongest reaction areas."},
  {front:"Can OTE hold for weeks before price reverses?",back:"Yes. $COIN chilled at 0.618 for ~17 days before the reversal triggered. Price can tap and stay inside OTE for days, weeks, even longer — it's a probability zone, not a timer. Time is your friend when thesis is intact."},
  {front:"OTE tells you ___. #TheStrat tells you ___.",back:"OTE tells you WHERE. #TheStrat tells you WHEN. You need both. A fib tap without a trigger is just a level on the chart. A Strat signal without a fib context lacks the probability advantage. Together they're a cheat code."},
  {front:"Price taps OTE. What do you do first?",back:"Pay attention — don't enter yet. OTE is a probability zone, not an entry signal. Wait for #TheStrat to give you the trigger (hammer, 1-3, double inside, 2-2 rev, CCRP). Price can tap OTE and reverse immediately, or chill there for weeks, or break below. No signal = no entry."},
  {front:"What Strat signals work best at OTE?",back:"Hammers (wick rejection), 1-3 setups with bullish close, double inside bars (primed for extension), shooters (for shorts), 2-2 reversals (clear directional flip), CCRPs (the most powerful — inside-bar consolidation with continuity flipping your direction)."},
  {front:"What's the most powerful Strat combo at OTE?",back:"A CCRP at OTE. Combines inside-bar consolidation with Full Timeframe Continuity flipping in your direction — all happening at the highest-probability reversal zone. Inside bar at OTE is one of Adex's favorite setups."},
  {front:"What invalidates an OTE trade?",back:"A candle CLOSE below 0.786 on your thesis timeframe. A wick through doesn't count. A daily wick to 0.80 that closes at 0.70 is still a valid OTE hold. Higher-TF closes prevail — don't let lower-TF noise shake you off a weekly thesis."},
  {front:"The $SPY April 2025 reversal had what macro OTE context?",back:"Monthly chart tapping 0.618 of the 2022-low to 2025-high swing. Monthly hammer closed strong at high. 2-week showed double hammer + inside bar + CCRP. Weekly had 1-3 closed at high. All fractal timeframes aligned at the macro fib tap — textbook setup."},
  {front:"What's the 'bus analogy' applied to the SPY April reversal?",back:"Weekly 1-3-2u triggered first — weekly got on the bus. Target hit passed the baton to 2-week. 2-week 2-1-2u triggered, passed to the monthly. Monthly 2-2 rev triggered the CCRP, new all-time high. Lower-TF triggers each unlocked the next higher-TF target."},
  {front:"What's the 'Abby Model'?",back:"A downtrend makes its first attempt at a higher high (displacement), then retraces into OTE on that new leg. The reversal back to the prior highs becomes high-probability — especially when Strat signals confirm the OTE bounce. The $AAT setup was a textbook Abby Model."},
  {front:"$AAT's first OTE entry failed on the 2-day double-inside break. What did Adex do next?",back:"Got stopped out, then kept watching $AAT because it was still at OTE. The next week closed as a hammer at 0.618. The following week triggered 2-2 rev on weekly, which triggered outside 2-week → CCRP setup. He re-entered and rode the move to target. One failed entry doesn't kill a valid OTE setup."},
  {front:"$COIN chilled at OTE for 17 days. What timeframe finally revealed the setup?",back:"The 6-day chart. The daily, 2-day, 3-day, 4-day, 5-day all looked choppy. But the 6-day produced a 1-3 with a CCRP and four wicks all bouncing off 0.5. When price is at OTE and you can't see the setup on your primary TFs, check all fractal timeframes — one will show it."},
  {front:"What was the $WFC Strat+OTE setup?",back:"Uptrend with displacement down into 0.618. Weekly closed as a bullish hammer with an inside-2-week setup. CCRP at OTE — inside bar + fib tap + higher-TF continuity all aligned. Triggered up, took out displacement high, continued higher."},
  {front:"When should you use OTE with leap-style options?",back:"When price hits a MACRO OTE (monthly, quarterly, yearly swings). The chart isn't telling you a $10 move — it's telling you the break-of-structure target could be $30-50 away. Higher-TF OTE = higher-TF target = longer time to buy = leaps. Don't buy weeklies on monthly OTE setups."},
  {front:"Why do some traders skip Strat triggers until price pulls into OTE?",back:"Because entries at OTE have better risk-to-reward than entries at the initial trigger. A weekly 2-1-2u that triggers Monday often pulls back into OTE Tuesday-Wednesday before continuing. Waiting for OTE = better entry, smaller invalidation, more profit on the same exit target."},
  {front:"What's Adex's final takeaway on OTE?",back:"OTE is the most probable zone for reversal. When you see price tap OTE with Strat confluence (inside bar, 1-3, hammer), you're salivating — because your edge just lined up with the highest-probability entry zone. That's the cheat code: favorite Strat combo + OTE tap."},
];

export default function Flashcards(){
  const[deck,setDeck]=useState([...CARDS]);const[idx,setIdx]=useState(0);const[flipped,setFlipped]=useState(false);
  const[known,setKnown]=useState(new Set());const[reviewing,setReviewing]=useState(new Set());const[animDir,setAnimDir]=useState(null);
  const current=deck[idx];const total=deck.length;const progress=((known.size+reviewing.size)/CARDS.length)*100;
  const flip=useCallback(()=>setFlipped(f=>!f),[]);
  const next=useCallback((st)=>{const id=deck[idx].front;if(st==="known"){setKnown(p=>new Set([...p,id]));setReviewing(p=>{const n=new Set(p);n.delete(id);return n;});setAnimDir("right");setTimeout(()=>{setFlipped(false);setAnimDir(null);setDeck(prev=>{const nd=[...prev];nd.splice(idx,1);return nd.length?nd:prev;});setIdx(i=>i>=deck.length-1?0:i);},250);}else{setReviewing(p=>new Set([...p,id]));setKnown(p=>{const n=new Set(p);n.delete(id);return n;});setAnimDir("left");setTimeout(()=>{setFlipped(false);setAnimDir(null);setDeck(prev=>{const nd=[...prev];const card=nd.splice(idx,1)[0];nd.push(card);return nd;});setIdx(i=>i>=deck.length-1?0:i);},250);}},[deck,idx]);
  const shuffle=useCallback(()=>{setDeck([...CARDS].sort(()=>Math.random()-0.5));setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  const reset=useCallback(()=>{setDeck([...CARDS]);setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  useEffect(()=>{const h=(e)=>{if(e.code==="Space"){e.preventDefault();flip();}if(e.code==="ArrowRight")next("known");if(e.code==="ArrowLeft")next("review");};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h);},[flip,next]);
  return(
    <div style={{minHeight:"100vh",background:`linear-gradient(135deg,${BLACK} 0%,#1a1510 100%)`,fontFamily:"'Segoe UI',system-ui,sans-serif",padding:"20px",boxSizing:"border-box"}}>
      <div style={{textAlign:"center",marginBottom:20}}><div style={{color:GOLD,fontSize:11,letterSpacing:3,fontWeight:700,marginBottom:4}}>ADEXTRADES UNIVERSITY</div><div style={{color:"#fff",fontSize:22,fontWeight:700}}>Lesson #7 Flashcards</div><div style={{color:"#888",fontSize:13,marginTop:2}}>The Strat + Optimal Trade Entry</div></div>
      <div style={{maxWidth:500,margin:"0 auto 16px",display:"flex",gap:12,alignItems:"center"}}><div style={{flex:1,height:6,background:"#2a2a2a",borderRadius:3,overflow:"hidden"}}><div style={{height:"100%",width:`${progress}%`,background:`linear-gradient(90deg,${GOLD},#e8c85a)`,borderRadius:3,transition:"width 0.4s"}}/></div><div style={{color:"#888",fontSize:12,whiteSpace:"nowrap"}}>{known.size+reviewing.size}/{CARDS.length}</div></div>
      <div style={{maxWidth:500,margin:"0 auto 20px",display:"flex",justifyContent:"center",gap:20}}>{[{c:GREEN,l:"Mastered",v:known.size},{c:RED_C,l:"Review",v:reviewing.size},{c:"#555",l:"Unseen",v:CARDS.length-known.size-reviewing.size}].map(({c,l,v})=>(<div key={l} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:8,height:8,borderRadius:"50%",background:c}}/><span style={{color:"#aaa",fontSize:12}}>{l}: {v}</span></div>))}</div>
      <div style={{maxWidth:500,margin:"0 auto",perspective:1000}}>
        <div onClick={flip} style={{cursor:"pointer",position:"relative",height:320,transformStyle:"preserve-3d",transition:animDir?"transform 0.25s, opacity 0.25s":"transform 0.5s",transform:`${flipped?"rotateY(180deg)":"rotateY(0)"} ${animDir==="right"?"translateX(60px)":animDir==="left"?"translateX(-60px)":""}`,opacity:animDir?0.3:1}}>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",background:`linear-gradient(145deg,${CHARCOAL},#222)`,border:`2px solid ${GOLD}40`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"30px 28px",boxSizing:"border-box"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:16,opacity:0.7}}>QUESTION</div><div style={{color:"#fff",fontSize:17,textAlign:"center",lineHeight:1.5,fontWeight:500}}>{current.front}</div><div style={{color:"#666",fontSize:11,marginTop:"auto",paddingTop:12}}>Tap to flip</div></div>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",transform:"rotateY(180deg)",background:`linear-gradient(145deg,#1a1508,#1e1a10)`,border:`2px solid ${GOLD}`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"22px 26px",boxSizing:"border-box",overflow:"auto"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:10}}>ANSWER</div><div style={{color:"#e8e0d0",fontSize:13,textAlign:"center",lineHeight:1.6}}>{current.back}</div></div>
        </div>
      </div>
      <div style={{textAlign:"center",color:"#666",fontSize:12,margin:"12px 0"}}>Card {idx+1} of {total}</div>
      <div style={{maxWidth:500,margin:"0 auto",display:"flex",gap:12,justifyContent:"center"}}>{[{label:"← Review Again",color:RED_C,action:"review"},{label:"Got It →",color:GREEN,action:"known"}].map(({label,color,action})=>(<button key={action} onClick={()=>next(action)} style={{flex:1,padding:"14px 0",background:"transparent",border:`2px solid ${color}`,color,borderRadius:10,fontSize:14,fontWeight:700,cursor:"pointer",transition:"all 0.2s"}} onMouseEnter={e=>e.target.style.background=color+"20"} onMouseLeave={e=>e.target.style.background="transparent"}>{label}</button>))}</div>
      <div style={{maxWidth:500,margin:"16px auto 0",display:"flex",gap:10,justifyContent:"center"}}><button onClick={shuffle} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>🔀 Shuffle</button><button onClick={reset} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>↺ Reset</button></div>
      <div style={{textAlign:"center",color:"#444",fontSize:11,marginTop:16}}>Space = flip · ← = review · → = got it</div>
    </div>);
}
