"use client";
import { useState, useCallback, useEffect } from "react";
const GOLD="#D4A843",BLACK="#0D0D0D",CHARCOAL="#1A1A1A",GREEN="#2ECC71",RED_C="#E74C3C";

const CARDS=[
  {front:"What's the very first question to ask when building a thesis?",back:"What timeframe is your thesis based on? Pick your thesis timeframe BEFORE looking for confluences — otherwise you'll cherry-pick signals to confirm your bias. The thesis timeframe is the chart where your primary setup lives."},
  {front:"What does 'the reason you enter is the reason you exit' mean?",back:"If you entered because of a specific Strat combo (e.g., a 2-1-2u), your invalidation is the opposite of that setup (a 2-1-2d close). Your exit logic must be defined by the same framework as your entry logic — not by P&L or gut feeling."},
  {front:"Your bias is a 2-1-2u. What invalidates it?",back:"A candle CLOSE below the inside bar (i.e., a 2-1-2d) on your thesis timeframe. Above the inside bar = trigger fires. Below the inside bar = invalidation. The level matters only when a candle closes through it."},
  {front:"Your bias is a 2-1-2d. What invalidates it?",back:"A candle CLOSE above the inside bar (i.e., a 2-1-2u) on your thesis timeframe. The opposite Strat combo is always your invalidation signal."},
  {front:"Does a wick through invalidation count as invalidation?",back:"No. Invalidation requires a candle CLOSE beyond the level on your thesis timeframe. Wicks are normal price noise — often liquidity sweeps. Don't exit on wicks."},
  {front:"Why is invalidation defined by 'candle close,' not just touching the level?",back:"Because price touches levels all the time during normal price action. Only a close beyond the level means buyers/sellers committed to that direction during that full session. Close = commitment. Wick = exploration."},
  {front:"What are the TWO patterns that can invalidate a 2-1-2u bias?",back:"1) Outside-bar reversal — a single candle closes below the inside bar's low. 2) A 1-2-2 reversal — two sequential candles where the second closes below the trigger. Together, a 1-2-2 is essentially a 3 bar on the next-higher timeframe."},
  {front:"What happens when a bias triggers (trigger fires)?",back:"Assuming other confluences are in your favor, there are only two outcomes: price goes to your target, OR price invalidates with a candle close beyond your invalidation level. No third option. No 'maybe' — it's binary."},
  {front:"Why do traders commonly ignore invalidation signals?",back:"Human emotion. When a position invalidates, the brain looks for reasons to stay in — 'what if the next candle reverses?' That subjectivity is exactly what the Strat removes. If price objectively invalidated, you should objectively be out."},
  {front:"What's 'confluence equals confidence'?",back:"The more confluences you have for a trade — across pillars, across timeframes — the higher the probability the setup plays out. A setup with 10 confluences beats a setup with 2. Stack signals before entering."},
  {front:"How many confluences should you aim for per setup?",back:"5 to 10 minimum. On Strat-rich charts, you'll often find 15+ confluences (the lesson's $AAOK example hit 16 bullish). Anything under 3 is too thin to trade."},
  {front:"What are the main categories of confluences to check?",back:"Sector alignment, FTFC, gap fills, technical analysis (trends/supply/demand), market structure (BOS/MSS/OTE/liquidity), Strat combos across timeframes, and charting basics (hammers, shooters, strong candles, CCRP)."},
  {front:"Why should you build BOTH a bullish AND a bearish confluence list for every chart?",back:"To remove bias. If you only look for signals that support your initial lean, that's confirmation bias. A true edge is when one side dramatically outweighs the other (16 vs 4). If the counts are close, the trade isn't there — move on."},
  {front:"In the $AAOK example, what was the bull vs bear count?",back:"16 bullish confluences vs 4 bearish. Even the bearish items (potential retrace into bullish OTE, possible supply sweep) didn't truly invalidate the bullish thesis — they just described possible paths before the eventual move up. Clearly dominant bullish thesis."},
  {front:"What is a 'machine gun trigger'?",back:"When multiple Strat setups across different timeframes stack within a tight price range. A single candle can trigger all of them at once, cascading targets across timeframes. These are explosive pathways — high probability because each target becomes the next entry."},
  {front:"What's the 'icing on the cake' confluence?",back:"The ONE confluence that tells you personally 'I'm definitely taking this trade.' For Adex, it's FTFC. For Abi, it's market structure. Different traders have different personal signals — find yours through back-testing. It's the one that converts 'maybe' to 'yes.'"},
  {front:"How do you label triggers to find machine gun setups?",back:"For every timeframe on the chart, mark the price level where a Strat combo would trigger. If you see multiple triggers clustered within a few cents/dollars, that's a machine gun setup. Label targets the same way to see pathway cascades."},
  {front:"Bullish and bearish confluences are close in count (e.g., 7 vs 6). What should you do?",back:"Skip the trade. Close counts mean the chart doesn't have clarity. The setup isn't there. Move on to the next ticker. The best trades come from charts where one direction dramatically outweighs the other."},
  {front:"You have a 2-1-2u bias on the weekly. Which chart do you monitor for invalidation?",back:"The weekly chart. Your thesis timeframe is where your invalidation plays out. Daily wicks and lower-TF noise are irrelevant. Only a weekly candle close below the weekly inside bar invalidates your weekly thesis."},
  {front:"Why does your participant timeframe usually match the highest timeframe that triggered?",back:"Because higher timeframes carry more magnitude. If the weekly, 2-week, and 4-week all trigger, becoming a 4-week participant gives you the biggest target and the most time for the setup to play out. Your invalidation moves to that 4-week inside bar level."},
];

export default function Flashcards(){
  const[deck,setDeck]=useState([...CARDS]);const[idx,setIdx]=useState(0);const[flipped,setFlipped]=useState(false);
  const[known,setKnown]=useState(new Set());const[reviewing,setReviewing]=useState(new Set());const[animDir,setAnimDir]=useState(null);
  const current=deck[idx];const total=deck.length;const progress=((known.size+reviewing.size)/CARDS.length)*100;
  const flip=useCallback(()=>setFlipped(f=>!f),[]);
  const next=useCallback((st)=>{const id=deck[idx].front;if(st==="known"){setKnown(p=>new Set([...p,id]));setReviewing(p=>{const n=new Set(p);n.delete(id);return n;});setAnimDir("right");setTimeout(()=>{setFlipped(false);setAnimDir(null);setDeck(prev=>{const nd=[...prev];nd.splice(idx,1);return nd.length?nd:prev;});setIdx(i=>i>=deck.length-1?0:i);},250);}else{setReviewing(p=>new Set([...p,id]));setKnown(p=>{const n=new Set(p);n.delete(id);return n;});setAnimDir("left");setTimeout(()=>{setFlipped(false);setAnimDir(null);setDeck(prev=>{const nd=[...prev];const card=nd.splice(idx,1)[0];nd.push(card);return nd;});setIdx(i=>i>=deck.length-1?0:i);},250);}},[deck,idx]);
  const shuffle=useCallback(()=>{setDeck([...CARDS].sort(()=>Math.random()-0.5));setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  const reset=useCallback(()=>{setDeck([...CARDS]);setIdx(0);setFlipped(false);setKnown(new Set());setReviewing(new Set());},[]);
  useEffect(()=>{const h=(e)=>{if(e.code==="Space"){e.preventDefault();flip();}if(e.code==="ArrowRight")next("known");if(e.code==="ArrowLeft")next("review");};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h);},[flip,next]);
  return(
    <div style={{minHeight:"100vh",background:`linear-gradient(135deg,${BLACK} 0%,#1a1510 100%)`,fontFamily:"'Segoe UI',system-ui,sans-serif",padding:"20px",boxSizing:"border-box"}}>
      <div style={{textAlign:"center",marginBottom:20}}><div style={{color:GOLD,fontSize:11,letterSpacing:3,fontWeight:700,marginBottom:4}}>ADEXTRADES UNIVERSITY</div><div style={{color:"#fff",fontSize:22,fontWeight:700}}>Lesson #10 Flashcards</div><div style={{color:"#888",fontSize:13,marginTop:2}}>Building Your Trade Thesis</div></div>
      <div style={{maxWidth:500,margin:"0 auto 16px",display:"flex",gap:12,alignItems:"center"}}><div style={{flex:1,height:6,background:"#2a2a2a",borderRadius:3,overflow:"hidden"}}><div style={{height:"100%",width:`${progress}%`,background:`linear-gradient(90deg,${GOLD},#e8c85a)`,borderRadius:3,transition:"width 0.4s"}}/></div><div style={{color:"#888",fontSize:12,whiteSpace:"nowrap"}}>{known.size+reviewing.size}/{CARDS.length}</div></div>
      <div style={{maxWidth:500,margin:"0 auto 20px",display:"flex",justifyContent:"center",gap:20}}>{[{c:GREEN,l:"Mastered",v:known.size},{c:RED_C,l:"Review",v:reviewing.size},{c:"#555",l:"Unseen",v:CARDS.length-known.size-reviewing.size}].map(({c,l,v})=>(<div key={l} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:8,height:8,borderRadius:"50%",background:c}}/><span style={{color:"#aaa",fontSize:12}}>{l}: {v}</span></div>))}</div>
      <div style={{maxWidth:500,margin:"0 auto",perspective:1000}}>
        <div onClick={flip} style={{cursor:"pointer",position:"relative",height:320,transformStyle:"preserve-3d",transition:animDir?"transform 0.25s, opacity 0.25s":"transform 0.5s",transform:`${flipped?"rotateY(180deg)":"rotateY(0)"} ${animDir==="right"?"translateX(60px)":animDir==="left"?"translateX(-60px)":""}`,opacity:animDir?0.3:1}}>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",background:`linear-gradient(145deg,${CHARCOAL},#222)`,border:`2px solid ${GOLD}40`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"30px 28px",boxSizing:"border-box"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:16,opacity:0.7}}>QUESTION</div><div style={{color:"#fff",fontSize:17,textAlign:"center",lineHeight:1.5,fontWeight:500}}>{current.front}</div><div style={{color:"#666",fontSize:11,marginTop:"auto",paddingTop:12}}>Tap to flip</div></div>
          <div style={{position:"absolute",inset:0,backfaceVisibility:"hidden",transform:"rotateY(180deg)",background:`linear-gradient(145deg,#1a1508,#1e1a10)`,border:`2px solid ${GOLD}`,borderRadius:16,display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",padding:"22px 26px",boxSizing:"border-box",overflow:"auto"}}><div style={{color:GOLD,fontSize:10,letterSpacing:2,fontWeight:700,marginBottom:10}}>ANSWER</div><div style={{color:"#e8e0d0",fontSize:13,textAlign:"center",lineHeight:1.6}}>{current.back}</div></div>
        </div>
      </div>
      <div style={{textAlign:"center",color:"#666",fontSize:12,margin:"12px 0"}}>Card {idx+1} of {total}</div>
      <div style={{maxWidth:500,margin:"0 auto",display:"flex",gap:12,justifyContent:"center"}}>{[{label:"← Review Again",color:RED_C,action:"review"},{label:"Got It →",color:GREEN,action:"known"}].map(({label,color,action})=>(<button key={action} onClick={()=>next(action)} style={{flex:1,padding:"14px 0",background:"transparent",border:`2px solid ${color}`,color,borderRadius:10,fontSize:14,fontWeight:700,cursor:"pointer",transition:"all 0.2s"}} onMouseEnter={e=>e.target.style.background=color+"20"} onMouseLeave={e=>e.target.style.background="transparent"}>{label}</button>))}</div>
      <div style={{maxWidth:500,margin:"16px auto 0",display:"flex",gap:10,justifyContent:"center"}}><button onClick={shuffle} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>🔀 Shuffle</button><button onClick={reset} style={{padding:"8px 20px",background:"#2a2a2a",color:"#aaa",border:"1px solid #3a3a3a",borderRadius:8,fontSize:12,cursor:"pointer"}}>↺ Reset</button></div>
      <div style={{textAlign:"center",color:"#444",fontSize:11,marginTop:16}}>Space = flip · ← = review · → = got it</div>
    </div>);
}
